Genesis-Embodied-AI/Genesis

- pyproject.toml
`pip install -e ".[render]"` in [doc](https://genesis-world.readthedocs.io/en/latest/user_guide/getting_started/visualization.html#setup)
> dependencies following doc for rendering

- examples/rigid/apply_external_force_torque.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
Add apply_links_external_force/torque in RigidSolver
Add example
> add apply_external_force/torque

- README.md
- README_CN.md
Enhance the README with visually appealing badges and update the Chinese version for better accessibility.
> Add badges and update Chinese README

- CONTRIBUTING.md
- README_CN.md
- enhanced readability
- adjusted title format [MD001/heading-increment]
> Updated README_CN and CONTRIBUTING

- examples/drone/hover_env.py
- examples/drone/hover_eval.py
- examples/drone/hover_train.py
This pull request introduces a new reinforcement learning environment for **drone hovering**, along with the necessary training and evaluation scripts. The environment is designed to train a drone to maintain a stable hover position using reinforcement learning algorithms.
https://github.com/user-attachments/assets/27b72a63-6943-4fdc-9d2d-c5dd5d04cfcf
1. **Environment Implementation (`hover_env.py`):**
- Added `HoverEnv` class which defines the drone hovering environment.
- Implemented reward functions: `_reward_target`, `_reward_smooth`, and `_reward_crash` to provide feedback to the agent.
2. **Training Script (`hover_train.py`):**
- Added a script to train the drone hovering policy using the `HoverEnv` environment.
- Defined configuration functions `get_train_cfg` and `get_cfgs` to set …
> Add Drone Hovering Reinforcement Learning Environment and Training Scripts

- genesis/utils/mjcf.py
load box texture when parsing mjcf
> load box texture when parsing mjcf

- README.md
- README_CN.md
- README_FR.md
- README_JA.md
- README_KR.md
> [MISC] Add README_KR.md

- genesis/utils/urdf.py
> remove duplicated code

- genesis/ext/pyrender/trackball.py
Fix the AttributeError in the `Trackball` class by initializing `_pdown` and handling its usage correctly.
* Initialize `_pdown` attribute to `None` in the `__init__` method.
* Modify the `drag` method to handle the case where `_pdown` is not set by defaulting to the current point.
* Update the `drag` method to interpret drag as a roll about the camera axis and handle different states (rotate, roll, pan) correctly.
> Fix AttributeError in Trackball class

- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/vis/raytracer.py
> [BUG FIX] _id to uid

- examples/drone/README.md
- examples/drone/hover_env.py
- examples/drone/hover_eval.py
- examples/drone/hover_train.py
1. improve **algo hyper params**. In `hover_train.py`
set `"entropy_coef": 0.004,`, for a better flight.
2. add **visualization while training**. For performance reason, the max render n env is set to 10.
https://github.com/user-attachments/assets/d6657208-5722-49db-be94-d41c9a91c4e6
4. update readme for #530 
Note: If you experience slow performance or encounter other issues during evaluation, try removing the `--record` option.
> [FEATURE] update HoverEnv, change hyper params, and visualization while training

- genesis/utils/geom.py
> [Bug Fix] fix geom util bug 

- genesis/engine/mesh.py
local variable 'opacity_texture' referenced before assignment when color_texture is None.
None
Bug fix
> [BUG FIX]  'opacity_texture' referenced before assignment

- genesis/engine/entities/rigid_entity/rigid_entity.py
Added `ls_idx_local` arg to `get_links_pos`, `get_links_quat`, `get_links_vel`, `get_links_ang` to match with other `get_links_*` API
N/A
> [FEATURE] add ls_idx_local to get_links_ methods

- examples/tutorials/draw_debug.py
- genesis/engine/scene.py
- genesis/ext/pyrender/mesh.py
- genesis/vis/rasterizer_context.py
Enable removing a single object instead removing all.
Resolves Genesis-Embodied-AI/Genesis#649
When debugging, it is desirable to choose which debug entities to keep and/or remove by users.
The change has been tested against the existing tests and examples.
Also, I have modified [the existing example](https://github.com/Genesis-Embodied-AI/Genesis/blob/main/examples/rigid/accelerometer_duck.py) using this change for testing purpose:
<details>
<summary>Click to toggle</summary>
```diff
import time
import argparse
import numpy as np
def main():
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--vis", action="store_true", default=False)
args = parser.parse_args()
gs.init(backend=gs.gpu) …
```
> [FEATURE] enable removing a single debug entity

- .gitignore
- genesis/ext/isaacgym/terrain_utils.py
- pyproject.toml
Fix to the recent terrain example.
Related to #674
> [MISC] fix to terrain example

- examples/rigid/terrain_subterrain.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/entities/rigid_entity/rigid_geom.py
- genesis/engine/entities/rigid_entity/rigid_link.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/options/morphs.py
Vertices of fixed entity (terrain for example) will not be batched to reduce memory cosumption.
Resolve #498.
See #498.
Run examples/rigid/terrain_subterrain.py
> [FEATURE] Support fixed entity

- pyproject.toml
INFO: pip is looking at multiple versions of genesis-world to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement tetgen==0.6.4 (from genesis-world) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.2, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.5)
ERROR: No matching distribution found for tetgen==0.6.4
> tetgen fix

- genesis/engine/entities/rigid_entity/rigid_entity.py
> [MISC] torch contact

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
> [BUG FIX] fix AABB

- genesis/utils/mjcf.py
Apply Zhenjia's change to MJCF parsing and add a warning for mjcf collision mesh's visualization.
Add a warning for #287 
```
gs.init(backend=gs.gpu)
)
plane = scene.add_entity(
gs.morphs.MJCF(
file="./arm26.xml",
),
vis_mode="collision",
)
scene.build()
for i in range(1000):
scene.step()
```
> [BUG] MJCF Parsing

- genesis/utils/mjcf.py
Reverts Genesis-Embodied-AI/Genesis#735
> Revert "[BUG] MJCF Parsing"

- genesis/engine/entities/rigid_entity/rigid_entity.py
This will fix #741 
This was due to the handling of envs_idx in non-parallel env. 
> [BUG FIX] Fix 741

- examples/drone/quadcopter_controller.py
- genesis/utils/mjcf.py
fix the texture issue of importing mjcf. 
This issue should have be solved; https://github.com/Genesis-Embodied-AI/Genesis/pull/735#issuecomment-2663956033
> [BUG FIX]  fix mjcf texture issue

- genesis/utils/mjcf.py
Fix the issue of mjcf parser. Skip loading texture when there is no geom texture.
> fix mjcf parser issue

- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/utils/mjcf.py
mujoco's qpos0 has 4 components (quaternion) for ball joints (3 dofs). Need to convert that quat to euler angle.
Now it can run cassie without error.
```
gs.init()
viewer_options = gs.options.ViewerOptions(
camera_pos=(0, -3.5, 2.5),
camera_lookat=(0.0, 0.0, 0.5),
camera_fov=40,
max_FPS=200,
)
viewer_options=viewer_options,
rigid_options=gs.options.RigidOptions(
dt=0.001,
contact_resolve_time=0.02,
),
)
########################## entities ##########################
plane = scene.add_entity(
morph=gs.morphs.Plane(),
)
path_robot = …
```
> [BUG FIX] Parse mujoco ball joint

- genesis/engine/entities/rigid_entity/rigid_entity.py
forward kinematics function for rigid entity
```python
import argparse
import numpy as np
def find_link_indices(entity, names):
if not names:
return []
link_indices = list()
for link in entity.links:
flag = False
for name in names:
if name in link.name:
flag = True
if flag:
link_indices.append(link.idx - entity.link_start)
return link_indices
def main():
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--vis", action="store_true", default=False)
args = parser.parse_args()
gs.init(seed=0, precision="32", logging_level="debug")
np.set_printoptions(precision=7, suppress=True) …
```
> [FEATURE] added FK

- genesis/ext/pyrender/viewer.py
- genesis/vis/viewer.py
Implement some fallback mechanism to try all onscreen rendering backends that may be available on a given platform, until to find one that is valid. If none, then it raises an exception as before. Moreover, the graphical window is only made visible once everything is all set. This avoids having multiple windows opening and closing until a valid backend is found. Besides, it makes sure the window is fully responsible once visible, instead of being "frozen" until the end of the compilation. 
Resolves Genesis-Embodied-AI/Genesis/issues/43
Resolves Genesis-Embodied-AI/Genesis/issues/336
Resolves Genesis-Embodied-AI/Genesis/issues/246
Resolves Genesis-Embodied-AI/Genesis/issues/352
Resolves Genesis-Embodied-AI/Genesis/issues/428
Resolves Genesis-Embodied-AI/Genesis/issues/336
Resolves …
> [BUG FIX] More robust onscreen display.

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
> [BUG FIX] remove debug print from get_links_acc()

- genesis/engine/entities/rigid_entity/rigid_entity.py
> [FEATURE] add set_mass method

- genesis/utils/mesh.py
fix mesh loading error when `image_index` is None.
> [BUG FIX] fix for 'list indices must be integers or slices, not NoneType'

- genesis/utils/mesh.py
Resolves Genesis-Embodied-AI/Genesis#831
> [BUG FIX] no image found for mesh

- genesis/engine/entities/rigid_entity/rigid_link.py
return with warning instead of raising an error for mass = 0 case.
> [BUG FIX] set mass handling of mass=0 case

- genesis/utils/geom.py
added torch version of R_to_quat
```python
from genesis.utils.geom import quat_to_R, R_to_quat
def test_R_to_quat():
for i in range(100):
quat = torch.randn(10, 4)
quat = quat / torch.norm(quat, dim=-1, keepdim=True)  # Normalize to ensure it's a valid unit quaternion
R = quat_to_R(quat)
quat_reconstructed = R_to_quat(R)
R_reconstructed = quat_to_R(quat_reconstructed)
assert torch.allclose(R, R_reconstructed, atol=1e-6), "Rotation matrix reconstruction failed!"
print("Test passed: R_to_quat is working correctly!")
```
> [FEATURE] add torch version of R_to_quat

- genesis/vis/visualizer.py
Add support for pyglet (1.5.31) so that trimesh show can run on the same environment. (also applies to the genesis.ext.trimesh)
trimesh viewer does not support pyglet>2, which is the current default for genesis. In case trimesh viewer is required, this adds support for 1.5.31 version. (we can keep the recommended version as >2)
> [FEATURE] add support for pyglet<2 so that genesis can be used with trimesh show

- genesis/engine/entities/rigid_entity/rigid_link.py
Resolves Genesis-Embodied-AI/Genesis/issues/848
> [BUG FIX] Fix contype overflow issue.

- pyproject.toml
relax taichi version because Mac Intel x86 does not have taichi 1.7.3
> [BUG FIX] relax taichi version because Mac Intel x86 does not have taichi 1.7.3

- genesis/constants.py
- genesis/utils/mjcf.py
This PR adds support for Mujoco type mjGEOM_ELLIPSOID.
Resolves Genesis-Embodied-AI/Genesis/issues/862
As stated in this original issue by @ale-amic1, "Adding the support of geom of type="ellipsoid" would enable the whole genesis community to leverage already existing models built for Mujoco and available in open source repositories like [mujoco_menagerie](https://github.com/google-deepmind/mujoco_menagerie/tree/main). Having access to more robot models improves the research work efficiency."
```python
fly = scene.add_entity(
gs.morphs.MJCF(
file=str("/path/to/fruitfly.xml"),
pos=(0, 0, 0),
),
)
```
> [FEATURE] Add support of Ellipsoid geometry.

- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/ext/pyrender/renderer.py
- genesis/utils/geom.py
- genesis/utils/misc.py
- genesis/vis/visualizer.py
This PR fixes pyglet backward compatibility on MacOS. It also provides Taichi-compatible Quaternion from-to Euler angles implementations. Finally, it improves exception reporting by (optionally) keeping track of the original cause.
> [MISC] Minor code cleanup. 

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
> [BUG FIX] Fix 'meaninertia' computation.

- genesis/engine/solvers/rigid/collider_decomp.py
- genesis/engine/solvers/rigid/constraint_solver_decomp.py
- genesis/engine/solvers/rigid/constraint_solver_decomp_island.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/ext/pyrender/viewer.py
This PR forces reset of the collision state after manually updating the configuration, which is not valid anymore.
> [BUG FIX] Reset collision detection state when setting qpos.

- genesis/_main.py
Adds `show_link_frame` option in `gs view`
It is a good practice to double check the link frame when encountered unintentional asset behavior.
> [FEATURE] Added show_link_frame option for the viewer for better debugging 

- genesis/__init__.py
`gs.raise_exception_from` was not defined (although it was in `gs.utils.misc`). added to __init__.py 
> [BUG FIX] fix gs.raise_exception_from error

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/utils/mjcf.py
Fix kp, kv loading from mjcf. Avoid always overwriting contact resolve time and use solparams from mjcf.
None
- [v] I read the **CONTRIBUTING** document.
- [v] I followed the `Submitting Code Changes` section of **CONTRIBUTING** document.
- [v] I tagged the title correctly (including BUG FIX/FEATURE/MISC/BREAKING)
- [v] I updated the [documentation](https://github.com/Genesis-Embodied-AI/genesis-doc) accordingly or no change is needed.
- [v] I tested my changes and added instructions on how to test it for reviewers.
> [BUG FIX] fix kp,kv; solparam

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
> [BUG FIX] Fix meaninertia (again!).

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
> [BUG FIX] fix potential zero div in meaninertia kernel

- genesis/engine/entities/rigid_entity/rigid_entity.py
Resolves Genesis-Embodied-AI/Genesis/issues/883
> [BUG FIX] Only add world link/joint if it has at least one geom.

- .github/workflows/ci.yml
- genesis/__init__.py
- genesis/constants.py
- genesis/engine/entities/rigid_entity/rigid_joint.py
- genesis/engine/solvers/rigid/collider_decomp.py
- genesis/engine/solvers/rigid/mpr_decomp.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/ext/pyrender/viewer.py
- genesis/logging/logger.py
- genesis/utils/geom.py
- genesis/utils/mesh.py
- genesis/utils/mjcf.py
- genesis/utils/urdf.py
- pyproject.toml
- tests/conftest.py
- tests/test_rigid_physics.py
- tests/utils.py
This PR mainly addresses a few minor discrepancies between Mujoco and Genesis. It also improves the reliability of the test utilities for comparing Mujoco with Genesis.
The objective is that Genesis perfectly matches Mujoco for a subset of features on simples cases. This would significantly reduce the amount of unit tests to implement in order to validate the physics by considering Mujoco as the ground truth. 
Resolves Genesis-Embodied-AI/Genesis/issues/651
Running the unit tests on my machine: `pytest -v tests/test_rigid_physics.py`
> [Misc] Various minor improvements.

- genesis/engine/entities/rigid_entity/rigid_entity.py
> [FEATURE] add envs_idx to get_links_net_contact_force

- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
> [BUG FIX] Fix bugs introduced by compound joint support.

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/utils/mjcf.py
- tests/test_rigid_physics.py
- tests/utils.py
> [MISC] Add kinematic unit test.

- examples/drone/fly.py
- examples/render_async.py
- genesis/_main.py
- genesis/ext/pyrender/viewer.py
- genesis/utils/tools.py
- genesis/vis/viewer.py
- genesis/vis/visualizer.py
This PR enforces the MacOS-friendly viewer management approach on all platforms whenever it is necessary. This means that all GUI processes are either managed by the main thread or completely separated processes instead of using child threads.
Resolves Genesis-Embodied-AI/Genesis#905
Supersedes Genesis-Embodied-AI/Genesis/pull/906
Having to maintain branching between MacOS and other platforms is problematic and must be avoided as much as possible.
Running `gs view genesis/assets/xml/franka_emika_panda/panda.xml`
>  [BUG FIX] Fix Genesis standalone viewer tool.

- .github/workflows/ci.yml
- .github/workflows/setup_env.sh
- genesis/__init__.py
- genesis/engine/solvers/rigid/collider_decomp.py
- pyproject.toml
- tests/test_rigid_benchmarks.py
- tests/test_rigid_physics.py
- tests/utils.py
This PR fixes several bugs in box-box collision detection algorithms, and adds more unit tests to make sure this will not happen again.
Resolves Genesis-Embodied-AI/Genesis/issues/893
The classical MPR collision detection algorithm is not very accurate, especially in non-strictly convex cases such as box-box collisions. Using a dedicated box-box collision detection algorithm is a common way to deal with this issue. However, the current implementation is buggy, preventing to enable it by default.
Running the new unit tests.
> [BUG FIX] Fix box-box collision detection.

- .github/workflows/ci.yml
- genesis/assets/urdf/3763/mobility.urdf
- genesis/assets/xml/humanoid.xml
- genesis/assets/xml/walker.xml
- genesis/constants.py
- genesis/engine/entities/rigid_entity/rigid_link.py
- genesis/engine/solvers/rigid/collider_decomp.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- pyproject.toml
- tests/conftest.py
- tests/test_rigid_physics.py
- tests/utils.py
This PR fixes several issues:
* Computation of 'invweight' for fixed bodies
* Computation of 'is_fixed' for bodies fixed wrt world
* Properly sanitize contact solver parameters for joints, geoms, and links
This detection of whether a body is fixed wrt has been broken since the introduction of compound joints, so it must be fixed. Moreover, the invweight of fixed body wrt their parent was never properly computed and should be fixed.
Addingunit test where a stickman model falls down on the ground under its own weight. It must lie on the ground without moving and no body parts going through the ground.
> [BUG FIX] Fix fixed body handling.

- .github/workflows/Dockerfile
- .github/workflows/ci.yml
- .github/workflows/setup_env.sh
> [BUG FIX] Fix CI on new runner.

- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/utils/urdf.py
- tests/test_rigid_physics.py
Support mimic joint in URDF
Resolves #678 
Resolves #129
> [FEATURE] Support mimic joint in URDF

- genesis/utils/mjcf.py
Fix loading actuators for tendons attached to more than 2 joints.
The current implementation assumes that only two joints are attached to a single tendon. This is very common but not part of the official MJCF specification. Let stop doing this hypothesis as it would break parsing of tendon actuators in such a case.
Loading the [fly model](https://github.com/google-deepmind/mujoco_menagerie/blob/main/flybody/fruitfly.xml) from mujoco_menagerie.
> [BUG FIX] Fix tendon fixed to more than 2 joints in MJCF.

- examples/rigid/closed_loop.py
- genesis/assets/xml/four_bar_linkage.xml
- genesis/assets/xml/four_bar_linkage_weld.xml
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/constraint_solver_decomp.py
- genesis/utils/geom.py
- genesis/utils/mjcf.py
- tests/test_rigid_physics.py
- tests/utils.py
Support Weld constraint.
Try 
```
python examples/rigid/closed_loop.py -v
```
> [FEATURE] Add weld constraint

- genesis/options/morphs.py
- genesis/utils/mesh.py
> [BUG FIX] Avoid useless convex decomposition.

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
Resolves Genesis-Embodied-AI/Genesis/discussions/927
> [BUG FIX] Fix too restrictive input valid check.

- examples/rigid/suction_cup.py
- genesis/engine/solvers/rigid/constraint_solver_decomp.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/options/solvers.py
- genesis/utils/geom.py
- tests/test_rigid_physics.py
Add suction cup such that two links can be attached together 
For example, attach cube and Franka's hand
```
rigid = scene.sim.rigid_solver
link_cube = np.array([cube.get_link("box_baselink").idx], dtype=gs.np_int)
link_franka = np.array([franka.get_link("hand").idx], dtype=gs.np_int)
rigid.add_weld_constraint(link_cube, link_franka)
```
Release
```
rigid.delete_weld_constraint(link_cube, link_franka)
```
The entire example: 
```
python examples/rigid/suction_cup.py
```
#291 
#435 
#681
> [FEATURE] Add suction cup

- genesis/vis/camera.py
Add a function to render world (or cam) frame point cloud from a camera.
Whoever need to render point cloud directly from camera.
Someone in the WeChat group is asking for it, it is also required by lists of robot learning settings.
Whoever need to render point cloud directly from camera.
in any test examples with a camera, run the following code
```
pc, mask = cam.render_pointcloud()
from plyfile import PlyData, PlyElement
def save_point_cloud_as_ply(points, filename):
"""
Saves a point cloud stored in a NumPy array as a PLY file using the plyfile library.
Args:
- points (np.ndarray): A NumPy array of shape (N, 3) containing the point cloud, where N is the number of points.
- filename (str): The filename of the output PLY file.
"""
dtype = [('x', 'f4'), ('y', 'f4'), ('z', 'f4')] …
```
> [Feature] Add render pointcloud to camera.py

- README.md
- README_FR.md
- genesis/__init__.py
- genesis/ext/pyrender/platforms/egl.py
- genesis/ext/pyrender/viewer.py
- genesis/vis/rasterizer_context.py
- genesis/vis/raytracer.py
- tests/test_rigid_benchmarks.py
> [MISC] Cleanup Genesis init / exit.

- examples/rigid/convex_decomposition.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/collider_decomp.py
- genesis/engine/solvers/rigid/constraint_solver_decomp.py
- genesis/engine/solvers/rigid/mpr_decomp.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/engine/solvers/rigid/sdf_decomp.py
- genesis/options/solvers.py
- genesis/utils/geom.py
- genesis/utils/mesh.py
- pyproject.toml
- tests/conftest.py
- tests/test_rigid_physics.py
- tests/utils.py
This PR improves the collision stability by using SDF as a fallback for scenarios where MPR is known to be unreliable (large geometry overlapping ratio), and warm-starting MPR with the previous contact normal as search direction (instead of vector going from one center to the other). It also improves the computation of the geometry center, that was very accurate previously, impeding the ability of MPR to find the exact contact information.
Convex decomposition is essential for dexterous manipulation, but enabling it requires accurate and stable collision detection, which was not the case so far.
Related to Genesis-Embodied-AI/Genesis/issues/975
Related to Genesis-Embodied-AI/Genesis/issues/986
> [BUG FIX] Improve contact stability.

- genesis/options/morphs.py
> fix logger issue

- examples/drone/hover_env.py
- examples/drone/hover_eval.py
- examples/drone/hover_train.py
- examples/locomotion/go2_backflip.py
- examples/locomotion/go2_env.py
- examples/locomotion/go2_eval.py
- examples/locomotion/go2_train.py
- examples/rigid/terrain_height_field.py
- genesis/__init__.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/entities/rigid_entity/rigid_joint.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/ext/pyrender/font.py
- genesis/ext/pyrender/renderer.py
- genesis/ext/pyrender/shader_program.py
- genesis/options/solvers.py
- genesis/vis/rasterizer.py
- genesis/vis/viewer.py
- genesis/vis/visualizer.py
- tests/conftest.py
- tests/test_rigid_physics.py
This PR implements several minor improvements:
* More robust successive init / destroy of Genesis (incl. viewer)
* Device management in RL examples has been improved to support Apple Metal
* Enable self-collision by default for Mujoco consistency
* Restore the ability to get entity com-based linear link's velocity
* Improve collision handling for inverse kinematics
* Warn about out-of-bound initial robot qpos
* Fix broken link reference in joint
Resolves Genesis-Embodied-AI/Genesis/issues/1000
Resolves Genesis-Embodied-AI/Genesis/issues/1003
Running drone hovering learning script locally on my machine.
> [MISC] Various minor improvements

- genesis/vis/rasterizer.py
> [BUG FIX] Fix genesis destroy.

- genesis/engine/mesh.py
Resolves Genesis-Embodied-AI/Genesis/issues/1010
> [BUG FIX] Fix mesh metadata for non-file morphs.

- genesis/engine/entities/fem_entity.py
- genesis/engine/solvers/fem_solver.py
- tests/test_fem.py
* Computes surface data including the number of surfaces in `FEMEntity.__init__` instead of `FEMEntity._add_to_solver` function.
* In `FEMSolver._kernel_add_elements`, use the number of vertices and elements of an added entity instead of total number of vertices or elements of all entities.
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/1013
This changes allows to add multiple FEM entities to a scene without errors.
We can test that we can add multiple FEM entities by running following test code:
```
import numpy as np
gs.init(seed=0, precision="32", logging_level="debug")
dt = 5e-4 …
```
> [BUG FIX] Fix issue when adding multiple FEM entities

- genesis/utils/geom.py
- tests/test_utils.py
Adds Rotation 6D util functions.
```python
def test_torch_round_trip():
print("Testing torch implementation...")
rot = R.random(10)
R_np = rot.as_matrix()
R_torch = torch.tensor(R_np, dtype=torch.float32)
d6 = R_to_rot6d(R_torch)
R_recon = rot6d_to_R(d6)
diff = torch.norm(R_torch - R_recon, dim=(-2, -1))
print("Max reconstruction error:", diff.max().item())
assert diff.max() < 1e-5
print("Torch test passed!")
def test_numpy_round_trip():
print("Testing numpy implementation...")
rot = R.random(10)
R_np = rot.as_matrix()
d6 = R_to_rot6d(R_np)
R_recon = rot6d_to_R(d6)
diff = np.linalg.norm(R_np - R_recon, axis=(-2, -1))
print("Max reconstruction error:", np.max(diff))
assert np.max(diff) < 1e-5
print("NumPy test passed!")
if __name__ …
```
> [FEATURE] rot6d utils

- examples/rigid/diffik_controller.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/collider_decomp.py
- genesis/ext/pyrender/viewer.py
- tests/test_rigid_physics.py
Fixes the example on Differential Inverse Kinematics.
The API returns a list of jacobian matrix for each env, even with `n_envs=0`.
```
Traceback (most recent call last):
File "/home/alexis/Documents/python/robotics/Genesis/examples/rigid/diffik_controller.py", line 95, in <module>
main()
File "/home/alexis/Documents/python/robotics/Genesis/examples/rigid/diffik_controller.py", line 86, in main
dq = jac.T @ np.linalg.solve(jac @ jac.T + diag, error)
~~~~^~~~~~~
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 1)
```
```
PYOPENGL_PLATFORM=glx python examples/rigid/diffik_controller.py -v -c -r ur5e
PYOPENGL_PLATFORM=glx python …
```
> [BUG FIX] fix dimension error in Differential Inverse Kinematics example

- genesis/__init__.py
- genesis/engine/entities/fem_entity.py
- genesis/engine/entities/hybrid_entity.py
- genesis/engine/entities/particle_entity.py
- genesis/engine/mesh.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/grad/creation_ops.py
- genesis/logging/logger.py
- genesis/utils/misc.py
- genesis/utils/particle.py
- pyproject.toml
There are bad practices here and there in the codebase that should be addressed. Not all of them can be addressed at once, but the easiest and most critical one are the following:
* `subprocess.Popen(..., shell=True)` is called directly instead of `subprocess.run(..., shell=False)`
* `tempfile.mkstemp` not being close nor deleted
* Additional tmp file being created manually by appending extension
* Return None instead of raising exception directly which breaks the traceback.
* Implementing low-level system-dependent methods manually such as `get_cpu_name`
* Using `torch.Tensor.contiguous` while the tensor is already guaranteed to be contiguous
* Storing error as string to postpone import error
* Using automatic code generation from python "template" plus `exec(eval(...)` instead of …
> [MISC] Code cleanup.

- docker/Dockerfile
- genesis/utils/particle.py
- genesis/vis/rasterizer_context.py
- genesis/vis/visualizer.py
- tests/test_rigid_physics.py
* Fix unit test flakyness
* Fix segfault at exit when enabling LuisaRender raytracing
* Fix genesis destroy on error if no display is available
* Fix broken LD_LIBRARY_PATH update due to double quote issue / syntax error
Resolves Genesis-Embodied-AI/Genesis/issues/1044
> [BUG FIX] Fix quote issue.

- genesis/utils/mesh.py
The current logic for convex decomposition would lead to unnecessary computation for robots. Ideally, we do not need this for articulated bodies.
> [MISC] Temporarily disable convex decomposition until we have a better logic for articulated robots

- genesis/ext/pyrender/trackball.py
This PR modifies the rotation logic to use an Azimuth/Elevation system in order to keep z-axis always up.
Resolves Genesis-Embodied-AI/Genesis/issues/1028
Currently, rotating the camera viewpoint in interactive viewer using mouse control feels very unnatural and hard to use because the z-axis does not always point upward. It would be better to match the behaviour of Mujoco and most common 3D viewers for robotics by enforcing the z-axis to point upward.
Running the tutorial and playing with the viewer.
> [FEATURE] Force interactive viewer camera Z-axis up.

- genesis/__init__.py
- genesis/_main.py
- genesis/engine/solvers/rigid/constraint_solver_decomp.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- tests/test_rigid_physics.py
* Fix 'gs view' segfault at exit.
* Remove exit trace fragile filtering.
* Enable nan test that was xfail.
* Adjust Genesis global eps to precision.
* Fix parallel envs info batching support.
Running the unit tests successfully.
> [BUG FIX] Various bug fixes.

- examples/rigid/accelerometer_franka.py
- examples/rigid/control_franka.py
- examples/rigid/domain_randomization.py
- examples/rigid/merge_entities.py
- examples/rigid/set_phys_attr.py
- examples/speed_benchmark/anymal_c.py
- examples/tutorials/control_your_robot.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/entities/rigid_entity/rigid_joint.py
- genesis/engine/entities/rigid_entity/rigid_link.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- tests/test_rigid_benchmarks.py
- tests/test_rigid_physics.py
- tests/utils.py
* Fix example scripts broken by PR#1053.
* Fix data accessor bugs introduced by PR#924.
* Add PD controller and batched env offscreen rendering unit tests.
Resolves https://github.com/Genesis-Embodied-AI/genesis-doc/issues/37
> [BUG FIX] Various minor bug fixes.

- genesis/ext/pyrender/platforms/egl.py
- tests/test_rigid_physics.py
> Fix user-specified EGL device being ignored.

- genesis/assets/xml/rope_ball.xml
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- tests/test_rigid_physics.py
qpos for ball joints is changed for euler to quat. Need to change `_kernel_set_dofs_position` accordingly.
Try
```
pytest --pdb -v -s --vis "tests/test_rigid_physics.py::test_rope_ball"
```
> [BUG FIX] fix set_dofs_position for ball joints

- genesis/assets/xml/rope_hinge.xml
> [BUG FIX] Add an asset to fix CI

- examples/rigid/multi_gpu.py
A simple way to run on multi-gpu utilizing multi-processing. Try
```
python examples/rigid/multi_gpu.py
```
> [FEATURE] Add an example for multi-gpu using multi processing

- examples/differentiable_push.py
- examples/tutorials/pbd_cloth.py
- genesis/engine/coupler.py
- genesis/engine/entities/fem_entity.py
- genesis/engine/entities/mpm_entity.py
- genesis/engine/entities/particle_entity.py
- genesis/engine/entities/pbd_entity.py
- genesis/engine/entities/rigid_entity/rigid_geom.py
- genesis/engine/entities/sph_entity.py
- genesis/engine/entities/tool_entity/mesh.py
- genesis/engine/entities/tool_entity/tool_entity.py
- genesis/engine/simulator.py
- genesis/engine/solvers/fem_solver.py
- genesis/engine/solvers/mpm_solver.py
- genesis/engine/solvers/pbd_solver.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/engine/solvers/sph_solver.py
- genesis/engine/states/entities.py
- genesis/engine/states/solvers.py
- genesis/utils/geom.py
- genesis/vis/rasterizer_context.py
- genesis/vis/raytracer.py
- tests/test_deformable_parallel.py
Enforce naming convention and change fort to address some of the comments in #1005 
> [MISC] Apply naming convention and change format

- genesis/engine/entities/hybrid_entity.py
- genesis/engine/solvers/mpm_solver.py
- Fix the naming issues introduced by #1096 
- Add batch dimension to `_kernel_update_soft_part_mpm`
Try 
```
python examples/tutorials/advanced_hybrid_robot.py
```
> [BUF FIX] fix naming; add batch dim to hybrid_entity

- genesis/engine/entities/tool_entity/tool_entity.py
- genesis/engine/states/entities.py
- genesis/engine/states/solvers.py
- require_grad=False for non-float variables
- Fix typos
Try
```
python examples/differentiable_push.py
```
- [] I have added tests to cover my changes.
> [BUG FIX] Fix diff push

- genesis/utils/gltf.py
> [BUG FIX] Fix missing argument

- genesis/options/morphs.py
- genesis/utils/urdf.py
> [BUG FIX] Fix scaling of poly-articulated robots.

- genesis/engine/solvers/rigid/collider_decomp.py
- genesis/engine/solvers/rigid/mpr_decomp.py
- tests/test_rigid_physics.py
> [BUG FIX] Encourages persistent contact points to improve physical stability.

- tests/conftest.py
> [MISC] Increase RAM memory per worker to avoid OOM error on CI.

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
We deliberately set timeconst to be zero for urdf and meshes so that it can fall back to the minimal value 2*dt.
> [MISC] Update time constant clipping warning.

- genesis/engine/solvers/rigid/collider_decomp.py
Add line feeds to doc string in collider_decomp.py
So I dont have to scroll horizontally backwards and forwards to read it.
> [DOC] Add line feeds to doc string

- examples/tutorials/advanced_hybrid_robot.py
- genesis/engine/entities/avatar_entity/avatar_entity.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/entities/rigid_entity/rigid_joint.py
- genesis/engine/solvers/rigid/constraint_solver_decomp.py
- genesis/engine/solvers/rigid/constraint_solver_decomp_island.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/options/solvers.py
- genesis/utils/geom.py
- genesis/utils/mjcf.py
- genesis/utils/urdf.py
- tests/conftest.py
- tests/utils.py
Fix input share issue for setting sol_params.
`_sanitize_sol_params` assumes 2D input but the function was expecting 1D array (`len(sol_params) == 7`)
So kept the input as 1D array and unsqueeze dim before `_sanitize_sol_params` and squeeze after it.
> [BUG FIX] fix shape issue

- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/utils/misc.py
- tests/test_rigid_physics.py
added an interface to get mass_matrix from rigid_entity
> [FEATURE] get mass_mat API

- genesis/engine/solvers/rigid/collider_decomp.py
On MacOS, the green cube is going through the ground when running suction unit test: `pytest -v -s -n 0 --vis "tests/test_rigid_physics.py::test_suction_cup[gpu-2]"`.
Everything is fine on Linux and Windows.
> [BUG FIX] Get around taichi compilation bug on MacOS.

- genesis/engine/solvers/rigid/collider_decomp.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/utils/misc.py
- tests/test_rigid_physics.py
> [BUG FIX] Various minor improvements and bug fixes.

- .github/workflows/generic-cpu.yml
- .github/workflows/linux-gpu.yml
- tests/test_rigid_physics.py
> [MISC] Fix CI flakyness.

- README.md
- genesis/utils/mesh.py
- genesis/utils/urdf.py
Resolves Genesis-Embodied-AI/Genesis/issues/1153
> [BUG FIX] Fix broken URDF parsing introduced by PR#1147.

- genesis/engine/solvers/rigid/collider_decomp.py
Since @ti.func is actually inlined and unrolled during compilation, we can reduce kernel length by reusing these functions. We could also try using @ti.real_func in the future for cleaner code.
The compile time for _func_narrow_phase is reduced from 138s to 68s on my side.
> [MIS] reduce compile time

- genesis/engine/entities/rigid_entity/rigid_equality.py
- genesis/engine/entities/rigid_entity/rigid_geom.py
- genesis/engine/entities/rigid_entity/rigid_joint.py
- genesis/engine/solvers/rigid/constraint_solver_decomp.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- tests/test_rigid_physics.py
- tests/utils.py
> [FEATURE] Add public API getter/setter for 'sol_params'.

- genesis/engine/coupler.py
- genesis/engine/solvers/sph_solver.py
Resolves Genesis-Embodied-AI/Genesis/issues/1172
> [BUG FIX] Fix 'get_acc' API mismatch for SPH solver.

- genesis/engine/mesh.py
- genesis/engine/scene.py
- genesis/options/morphs.py
- tests/test_rigid_physics.py
> [MISC] More robust decimation processing. Enable decimation by default.

- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- tests/test_rigid_physics.py
> [BUG FIX] Fix Rigid simulation without moving entities.

- .github/workflows/generic-cpu.yml
- .github/workflows/linux-gpu.yml
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- tests/test_rigid_physics.py
Supersedes https://github.com/Genesis-Embodied-AI/Genesis/pull/1181
Resolves Genesis-Embodied-AI/Genesis/issues/558
> [BUG FIX] Fix path planning obstacle avoidance.

- README.md
- README_CN.md
- README_FR.md
- README_JA.md
- README_KR.md
Fixing citation in README.
- Title "Genesis: A Universal and Universal Physics Engine for Robotics and Beyond" -> "Genesis: A Generative and Universal Physics Engine for Robotics and Beyond" to match with website.
- bibtex: "software" -> "misc" to better handle google scholar citations.
There are many paper used Genesis but not reflected on google scholar.
> [BUG FIX] update citation

- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/engine/solvers/rigid/support_field_decomp.py
- genesis/utils/geom.py
- genesis/utils/mjcf.py
- genesis/utils/urdf.py
- tests/test_rigid_physics.py
- tests/utils.py
Resolves Genesis-Embodied-AI/Genesis/issues/1204
Resolves Genesis-Embodied-AI/Genesis/issues/1135
> [BUG FIX] Fix URDF parsing bug introduced by #1169.

- examples/ddp_multi_gpu.py
Add an example for running genesis+torch on multi-gpu. Try
```
torchrun --standalone --nnodes=1 --nproc_per_node=2 examples/ddp_multi_gpu.py
```
> [FEATURE] Add multi gpu example using pytorch ddp

- genesis/engine/entities/rigid_entity/rigid_entity.py
Enable to return contacts with other entities only (excluding self collision)
> [FEATURE] add exclude_self_contact option

- examples/rigid/single_franka_envs.py
add `--horizon` to single_franka_envs.py, so we can run for differnet amounts of time.
By running with different values of `--horizon`
> [FEATURE] Make horizon configurable on single_franka_envs.py

- genesis/utils/misc.py
- pyproject.toml
- tests/conftest.py
- tests/test_rigid_physics.py
Resolves Genesis-Embodied-AI/Genesis/issues/1234
> [BUG FIX] Mitigate flakyness of the CI.

- genesis/engine/scene.py
- genesis/options/__init__.py
- genesis/options/profiling.py
- genesis/utils/warnings.py
- tests/test_utils.py
Add profiling options, to replace the standalone show_FPS option, and add FPS_tracker_alpha option
- backwards compatible: existing show_FPS can still b e used, but shows a deprecated warning message, once
By running https://github.com/hughperkins/taichi-play/blob/main/ndarray_perf/single_franka_envs.py
> [FEATURE] Add profiling options

- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- tests/conftest.py
- tests/test_rigid_physics.py
- tests/utils.py
> [BUG FIX] Fix links classical linear acceleration computation.

- genesis/engine/solvers/rigid/mpr_decomp.py
This issue was reporeted by the author of this repo, who uses a bunch of boxes to simulate stairs.
https://github.com/Albusgive/wheel_legged_genesis
Previously, simplex_support was pre-allocated for each geometry pair, which naturally supported parallel collision detection in the narrow phase. 
```
self.simplex_support = struct_support.field(
shape=self._solver._batch_shape((self._solver.n_geoms_, self._solver.n_geoms_, 4)),
layout=ti.Layout.SOA,
)
```
However, the disadvantage was that memory usage grew quadratically with respect to n_geoms_. Users simulating large scenes (>100 geometries, >4000 batch size) could suffer from out-of-memory (OOM) issues.
Since we are not running parallel collision detection across geometries, we can remove the extra two dimensions to better support large …
> [MISC] Delete geom axis in simplex

- genesis/engine/bvh.py
- tests/test_bvh.py
Added a new LBVH class that supports parallel tree construction and parallel query.
Added a new AABB class that wraps a field of aabbs.
LBVH build trees from AABB and can query AABBs.
None
The new BVH will be used for collision detection in the future.
Added a unit test in tests/test_bvh.py
> [FEATURE] New BVH using Linear BVH

- genesis/engine/scene.py
Fix `vis_options`'s annotation
> [BUG FIX] fix vis_options's annotation

- genesis/engine/solvers/rigid/collider_decomp.py
> [MISC] Reduce compile time.

- genesis/engine/solvers/rigid/constraint_solver_decomp.py
- tests/test_rigid_physics.py
Resolves Genesis-Embodied-AI/Genesis/issues/1282
> [BUG FIX] Fix net contact force attribute.

- genesis/logging/logger.py
Add `log` method to the Logger class wrapped by Genesis, so it could be used with `backoff`. 
Resolves Genesis-Embodied-AI/Genesis#1266
Add a log method to the Logger class wrapped by Genesis, so it could be used with other packages like backoff. Would love to use the beautiful Genesis logging theme consistently across other packages needed for projects developed on Genesis.
```python
import backoff
gs.init(backend=gs.gpu, logging_level='debug')
@backoff.on_exception(backoff.expo, Exception, max_tries=5, logger=gs.logger)
def foo():
print("Attempting to execute foo")
raise Exception("Simulated failure")
foo()
```
Before: 
[Genesis] [17:36:32] [ERROR] AttributeError: 'Logger' object has no attribute 'log'
After:
Attempting to execute foo
[Genesis] [17:36:02] [INFO] …
> [FEATURE] Add 'log' method in Logger to support backoff.

- genesis/engine/entities/rigid_entity/rigid_entity.py
Found a small bug that could potentially increase the IK speed up to x50. 
The `max_samples` loop was never exited after finding a solution; wasting remaining number of loops.  
Bug Fixed, Faster IK.
`pytest -k "test_inverse_kinematics[1-gpu]" tests/test_rigid_physics.py`
`pytest -k "test_inverse_kinematics[1-cpu]" tests/test_rigid_physics.py`
> [BUG FIX] fix IK loop bug

- README.md
- docker/Dockerfile.amdgpu
See https://github.com/Genesis-Embodied-AI/Genesis/pull/1299
> [FEATURE]: ROCm docker for AMD GPUs, with docs

- .github/workflows/linux-gpu.yml
- examples/drone/hover_env.py
- genesis/__init__.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/collider_decomp.py
- tests/conftest.py
- tests/test_rigid_benchmarks.py
- tests/test_rigid_physics.py
* Fix contact information retrieval
* Force running benchmarks on GPU
* Allow running benchmarks in parallel on different GPUs
> [BUG FIX] Fix contact information retrieval again.

- examples/drone/hover_env.py
Reverts Genesis-Embodied-AI/Genesis#1348
> Revert "[BUG FIX] Add angular damping to drone to prevent numerical instability"

- genesis/engine/entities/emitter.py
- genesis/engine/entities/rigid_entity/rigid_link.py
- genesis/engine/solvers/rigid/constraint_solver_decomp.py
- genesis/engine/solvers/rigid/constraint_solver_decomp_island.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/utils/geom.py
- genesis/utils/gltf.py
- genesis/utils/mesh.py
- genesis/vis/rasterizer_context.py
- genesis/vis/viewer.py
- tests/test_utils.py
* Refactor math helper methods to be more generic and improve performance.
* Speed up primitive mesh generation for viewer.
> [MISC] Various code cleanup and performance improvements.

- genesis/ext/pyrender/interaction/viewer_interaction.py
Note that `EVENT_HANDLE_STATE` is already imported in the `from .viewer_interaction_base import ViewerInteractionBase, EVENT_HANDLE_STATE` line
> [BUG FIX] fix EVENT_HANDLE_STATE

- genesis/vis/rasterizer_context.py
When the precision is 64, an error was thrown when rendering debug arrow. This was because of mismatch of data type from the branching. Specifically, in `z_up_to_R` function,
```
if out is None:
out_ = np.empty((*B, 3, 3), dtype=z.dtype)
else:
assert out.shape == (*B, 3, 3)
out_ = out
```
`out_` follows dtype of `z` if `out` is None, and follows that of `out` when it is not None. When `z` and `out` have different dtypes, `numba` throws an error.
> [BUGFIX] Fixed bug in rendering debug arrow when precision is 64

- examples/keyboard_teleop.py
- examples/rigid/convex_decomposition.py
- examples/tutorials/advanced_hybrid_robot.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/options/solvers.py
- genesis/utils/mesh.py
- genesis/utils/path_planing.py
- tests/test_hybrid.py
- tests/test_rigid_physics.py
- tests/utils.py
* Cleanup motion planning algorithm.
* Replace option 'constraint_timeconst' by 'constraint_timeconst_min'.
* Enable GJK by default.
> [MISC] Enable GJK collision detection algorithm by default.

- genesis/engine/solvers/rigid/collider_decomp.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/options/solvers.py
* Fix box-box collision detection algorithm.
* Enable box-box collision detection by default.
> Enable box-box collision detection by default.

- genesis/utils/geom.py
Fixed several typos that lead to bug in `geom.py`.
Resolves Genesis-Embodied-AI/Genesis#1445
> [BUG FIX] Fixed minor typos in geom.py

- genesis/_main.py
`range` should not be used for list
> [BUG FIX] Fix small bug in get_motors_info

- examples/coupling/fem_cube_linked_with_arm.py
- examples/rigid/terrain_subterrain.py
- genesis/engine/bvh.py
- genesis/engine/entities/particle_entity.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/entities/rigid_entity/rigid_link.py
- genesis/engine/scene.py
- genesis/engine/simulator.py
- genesis/engine/solvers/base_solver.py
- genesis/engine/solvers/fem_solver.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/ext/pyrender/mesh.py
- genesis/ext/pyrender/primitive.py
- genesis/ext/pyrender/scene.py
- genesis/utils/geom.py
- genesis/vis/rasterizer.py
- tests/test_render.py
- tests/test_rigid_physics.py
- tests/utils.py
* More exhaustive testing of rigid data accessors.
* Add unit test for debug draw.
* Fix Apple Metal support.
* Improve numerical robustness of '*_quat_to_xyz' helpers.
* Fix examples script 'fem_cube_linked_with_arm.py'
* Fix taichi warning about type casting.
> [BUG FIX] Various minor fixes.

- genesis/utils/misc.py
- genesis/vis/rasterizer_context.py
- genesis/vis/visualizer.py
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/1545
> [MISC] Allow following entity or mounting camera building scene.

- .github/workflows/generic.yml
- genesis/__init__.py
- genesis/engine/couplers/legacy_coupler.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/mpm_solver.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/utils/path_planing.py
- genesis/vis/camera.py
- tests/test_rigid_physics.py
* Enable antialiasing by default for BatchRender (for real).
* Filter out confusing tensor allocate warning for now.
* Cleanup IK method and fix non-contiguous memory exception.
* Raise exception calling 'control_dofs_(position|velocity)' with zero gains.
* Run unit tests for Python 3.12 only on Windows CI to reduce cost.
* Fix MPM with CPIC enabled but rigid solver not active.
> [BUG FIX] Various minor improvements and bug fixes.

- examples/tutorials/IK_motion_planning_grasp.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
Fix #1564 
Related PR #1575 #1576 
Try
```
python examples/tutorials/IK_motion_planning_grasp.py
```
> [Bug Fix] fix ik example

- README.md
- examples/rigid/ik_shadow_hand.py
- genesis/__init__.py
- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/scene.py
- genesis/engine/solvers/base_solver.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/utils/path_planning.py
- tests/test_integration.py
- tests/test_rigid_physics.py
* Cleanup init.
* Add support of taichi ndarray when saving scene.
* Increase tolerance of flaky unit test 'test_scene_saver_franka'.
* Avoid rigid solver import in planner.
* More comprehensive IK unit tests.
* Fix Inverse Kinematics algorithm (cont'd).
> [BUG FIX] Fix Inverse Kinematics algorithm (cont'd).

- genesis/ext/pyrender/viewer.py
The name `img_arr` was not defined.  
Resolves Genesis-Embodied-AI/Genesis#1603
> [BUG FIX] Fix NameError: name 'img_arr' is not defined in Pyrender.

- .readthedocs.yaml
Now the doc can be compiled based on the latest main
https://genesis-world.readthedocs.io/en/latest/
> [DOC] Update documentation so the doc will be compiled based on the latest main

- genesis/utils/misc.py
- pyproject.toml
- tests/test_rigid_physics.py
See https://github.com/Genesis-Embodied-AI/Genesis/pull/1642.
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/1622
> [MISC] Migration to gstaichi 2.1.1.

- genesis/vis/visualizer.py
with pyglet < 2.0, screen_height, screen_width, screen_scale was not defined.
> [BUG FIX] Fix support of 'pyglet<2.0'.

- examples/locomotion/go2_env.py
- genesis/engine/solvers/rigid/collider_decomp.py
- pyproject.toml
Reduce the memory usage for go2 example. (8G -> 2G)
Just try
```
python examples/locomotion/go2_train.py
```
> [MISC] reduce max_collision_pairs to save memory

- genesis/__init__.py
- genesis/engine/scene.py
- genesis/engine/solvers/mpm_solver.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/utils/misc.py
- tests/conftest.py
- tests/test_render.py
- tests/test_rigid_physics.py
- tests/test_utils.py
* Fix 'ti_to_torch' for good.
* Fix compound joints for 'set_dofs_position'.
* Fix support of legacy coupler for CPIC enabled.
* [CHANGING] More sensible defaults for camera far, near.
* Special handling of pytest parameter printing for types.
Related to https://github.com/Genesis-Embodied-AI/Genesis/issues/1593
> [BUG FIX, CHANGING] More sensible defaults for camera far, near. Fix compound joints for 'set_dofs_position'.

- genesis/engine/entities/rigid_entity/rigid_entity.py
- genesis/engine/solvers/rigid/rigid_solver_decomp.py
- genesis/utils/mjcf.py
- genesis/utils/urdf.py
- tests/test_fastcache_unified.py
- tests/test_rigid_physics.py
- tests/test_utils.py
Resolves Genesis-Embodied-AI/Genesis/issues/1694
Adding unit test 'test_robot_scale_and_dofs_armature' based on 'test_robot_scaling' (now removed).
> [BUG FIX, CHANGING] Fix invweight and meaninertia not always considering scale and dofs armature.

- pyproject.toml
Upgrade to gstaichi 2.3.1, which fixes two bugs in fastcache
> [MISC] Upgrade to gstaichi 2.3.1.

- .github/workflows/generic.yml
- examples/drone/fly_route.py
- tests/conftest.py
- tests/test_gstaichi.py
- tests/test_utils.py
Resolves Genesis-Embodied-AI/Genesis/issues/1714
> [MISC] Fix drone example.

- genesis/sensors/base_sensor.py
- genesis/sensors/contact_force.py
- genesis/sensors/imu.py
- genesis/sensors/sensor_manager.py
- genesis/utils/geom.py
- genesis/utils/misc.py
- genesis/utils/ring_buffer.py
- tests/conftest.py
- tests/test_sensors.py
Remove some code duplication, add at least two of each kind of sensors in tests and add fixture for 0 and 2 envs for coverage.
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/1722
Bug :(
`pytest tests/test_sensors.py`
> [BUG FIX] Add tests for adding multiple sensors and envs.

- examples/rigid/single_franka_envs.py
- genesis/recorders/file_writers.py
- tests/test_recorders.py
- tests/test_rigid_physics.py
Try
```
python examples/rigid/single_franka_envs.py -v -n 2
```
Should we include our examples in (daily, slow) CI? (I have the scripts for running examples as tests)
> [BUG FIX] fix single_franka_envs example

- .github/workflows/generic.yml
- genesis/utils/array_class.py
Add additional variable to cache key to make sure pure function works.
TODO:
move some of the dynamic properyies into field / ndarray
> [FEATURE] Enable pure function in CI

- genesis/utils/mjcf.py
Minor style cleanup on top of https://github.com/Genesis-Embodied-AI/Genesis/pull/1732.
> [BUG FIX] Fix logics for duplicating collision geometries as visual in MJCF.

- genesis/engine/entities/particle_entity.py
- genesis/grad/tensor.py
- tests/test_deformable_physics.py
- tests/test_render.py
- tests/test_rigid_physics.py
* Speedup 'test_robot_scale_and_dofs_armature' unit test by building scene once.
* Speedup 'test_segmentation_map' unit test by disabling some physics features.
* Speedup 'test_muscle' by avoiding forcing CPU backend.
* Speedup 'test_tet_primitive_shapes' unit test by tuning simu duration.
> [MISC] Speedup unit tests.

- genesis/engine/scene.py
- genesis/vis/rasterizer_context.py
- tests/conftest.py
- tests/test_render.py
> [FEATURE] Add method to update draw debug objects.

- .github/workflows/alarm.yml
- .github/workflows/examples.yml
- .github/workflows/production.yml
- examples/coupling/fem_cube_linked_with_arm.py
- examples/coupling/sand_wheel.py
- examples/coupling/sph_mpm.py
- examples/drone/interactive_drone.py
- examples/keyboard_teleop.py
- examples/pbd_liquid.py
- examples/render_async.py
- examples/rigid/convex_decomposition.py
- examples/sap_coupling/fem_fixed_constraint.py
- examples/sap_coupling/fem_sphere_and_cube.py
- examples/sap_coupling/franka_grasp_fem_sphere.py
- examples/sap_coupling/franka_grasp_rigid_cube.py
- examples/tutorials/advanced_muscle.py
- genesis/vis/raytracer.py
- tests/test_examples.py
- tests/utils.py
* Cleanup example unit tests.
* Fix PR alarm syntax error.
* More robust LuisaRender init.
* Update Production image to 1.2.
> [MISC] Cleanup example unit tests.

- pyproject.toml
Migrate to gstaichi 2.6.0
- migrate to in-house built llvm 15.0.7, as first step of upgrading to a more recent llvm
> [MISC] Migrate to gstaichi 2.6.0.
