Genesis-Embodied-AI/Genesis

genesis/vis/rasterizer_context.py

This pull request addresses issue #26 by ensuring an error message is displayed when the `trimesh`, `pyrender`, and/or `JITRenderer` modules fail to import due to a missing `ffmpeg` library, rather than allowing the process to fail silently.
Note that this use of `try/except` is still problematic and should probably be addressed in future updates. But at least this temporary fix will keep people from spending a lot of time trying to figure out the issue.

Fix silent FFMPEG failure

---

examples/locomotion/go2_env.py

In `go2_env.py`, the returned infos did not include `time_outs`, which led to the value bootstrapping in PPO not being used. As a result, `mean_action_std` kept increasing. This PR adds `time_outs` in the environment's info.

Include time_outs in environment info for PPO

---

README.md

Previously, the last item in the numbered "What is Genesis?" list was incorrectly labeled as "3." instead of "4.".
This commit updates the numbering to maintain consistency and clarity.

fix(docs): correct numbering in the "What is Genesis?" feature list

---

examples/locomotion/backflip/readme.md
examples/locomotion/go2_backflip.py
examples/locomotion/go2_train.py

Add single/double backflip checkpoints and evaluation code.
Update "base_init_quat" in env_cfg to wxyz

add backflip ckpts; update locomotion quaternion

---

examples/coupling/cloth_on_rigid.py

This PR sets the cpu option in the simulator when you use pass the `--cpu` arg in the `cloth_on_rigid.py` example
And thank you very much for making this simulator, I really enjoyed the few hours I could play around with it and look forward to be able to have a force-torque sensor soon :)

Fix cpu option in example

---

genesis/datatypes.py
genesis/options/options.py
genesis/repr_base.py

ANSI escape sequences (color and format control characters) used in the `__repr__` method may appear garbled in unsupported environments in debugging or terminal output, affecting the readability of debugger output or logging.
- The console of a debugger such as PyCharm or VSCode does not parse ANSI escape sequences correctly.
- Attribute values are displayed inconsistently across multiple lines, with some members being displayed as “gibberish”.
- Some property values may throw exceptions when accessed, resulting in no display.
Determine whether the current environment is a debug environment, so as to solve the problem of ANSI garbled code in the debug environment.
**Example of modified output**:
```text
<gs.Scene> t=<int>: 0 dt=<float>: 0.02 requires_grad=<bool>: False substeps=<int>: 2 …
```

Fix:Remove ANSI sequences and format issues in RBC.__repr

---

genesis/datatypes.py
genesis/options/options.py
genesis/repr_base.py

pr #186 has formatting issue and didn't pass ci
re-run black formatting

fix merge for ci from pr-186

---

CONTRIBUTING.md

[MISC] add CONTRIBUTING.md

---

genesis/ext/pyrender/viewer.py

This PR should resolve [Issue#91](https://github.com/Genesis-Embodied-AI/Genesis/issues/91).
On macOS, a Tk instance should be initiated before creating the viewer.

[BUG FIX] ext/pyrender/viewer: resolve macOS crashes when initialising Tk()

---

genesis/engine/entities/mpm_entity.py
genesis/engine/solvers/mpm_solver.py

Feature support for https://github.com/Genesis-Embodied-AI/Genesis/issues/190
New APIs: `mpm_entity.set/get_free`.
Non-free particles behave as boundary conditions.
Example code
```
gs.init()
sim_options=gs.options.SimOptions(
dt=4e-3,
substeps=10,
),
mpm_options=gs.options.MPMOptions(
lower_bound=(-0.5, -1.0, 0.0),
upper_bound=(0.5, 1.0, 1),
),
vis_options=gs.options.VisOptions(
visualize_mpm_boundary=True,
),
viewer_options=gs.options.ViewerOptions(
camera_fov=30,
res=(960, 640),
),
)
########################## entities ##########################
plane = scene.add_entity(
morph=gs.morphs.Plane(),
)
obj = …
```

[Feature] add particle free in MPM

---

examples/rigid/set_phys_attr.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_joint.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp_island.py
genesis/engine/solvers/rigid/contact_island.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/options/solvers.py

In the rigid solver option, there are `batch_links_info` and `batch_dofs_info`. If either is set to True, in the rigid solver, we introduce additional batch dimension (like in `links_state` or `dofs_state`). If they are both set to False, the built kernels in the solver should resemble those from the original code -- w/o the batch dimension.
An example is added in `examples/rigid/set_phys_attr.py`, which demonstrates how to set kp, kv, force range, armature, stiffness, invweight, damping for dofs and inertial mass, and invweight for links.
Related issues: https://github.com/Genesis-Embodied-AI/Genesis/issues/70, https://github.com/Genesis-Embodied-AI/Genesis/issues/120

[Feature] Allows to turn on/off batch (links/dofs) info

---

examples/drone/README.md
examples/drone/hover_env.py
examples/drone/hover_eval.py
examples/drone/hover_train.py

https://github.com/user-attachments/assets/aacc75e8-1712-4efe-8205-2d2ef49d2092
This pull request updates the hover environment to include random target point generation and improves the documentation to reflect these changes. The drone is now trained to reach randomly generated target points, enhancing the training process and making it more dynamic.
1. **Hover Environment Update (`hover_env.py`):**
- Updated the hover environment to **generate random target points** that the drone must reach.
- **Improved the reward functions** to provide feedback based on the drone's performance in reaching the target points.
- Enhanced the **visualization**.
2. **Training Script Update (hover_train.py):**
- Updated the training script to reflect the changes in the hover environment.
- Ensured that the …

Update Drone-Env with Random Target and Improved Documentation

---

examples/drone/hover_env.py

Added initialization of the target attribute in the `__init__` method of the `HoverEnv` class to ensure it is always defined.

[BUG FIX] fix AttributeError: 'HoverEnv' object has no attribute 'target'

---

genesis/engine/solvers/rigid/mpr_decomp.py

Increase precision to reduce eliminate some false positive cases.

[BUG FIX] modify mpr threshold

---

examples/rigid/ik_custom_chain.py
genesis/engine/entities/rigid_entity/rigid_entity.py

In `rigid_entity.inverse_kinematics_multilink`, we can specify multiple targets for IK with arguments `links`, `poss`, and `quats`.  This PR add a new argument `dofs_idx_local` in `rigid_entity.inverse_kinematics` and `rigid_entity.inverse_kinematics_multilink`. This argument allows to specify which dofs are to involved in the IK optimization.
High-level changes:
- (no change) we still compute the jacobian for all dofs since I haven't found a way to cleanly do this -- ti.func (`_func_get_jacobian`) does not take varying length array like `links_idx_by_dofs` (of length `n_links_by_dofs`) otherwise we can do something similar to the init q resampling.
- In the LM algorithm, we do all computations with the specified dofs only.
- When resampling initial q, we only consider the specified dofs. …

[feature] support custom ik chain

---

genesis/_main.py

Added `parser.print_help()` to ensure users receive guidance on available commands instead of the CLI failing silently.

Add default help message for gs CLI when no arguments are provided: _main.py

---

genesis/ext/urdfpy/utils.py

Fix typo in ValueError message for missing mesh in file in following file: genesis/ext/urdfpy/utils.py

[MISC] Fix typo in ValueError message for missing mesh

---

genesis/utils/geom.py

- fix the dimension issue in transform_quat_by_quat and transform_by_quat.
- remove transform_by_quat_yaw, which is not used at all.

[BUG FIX] Fix the dimensional issue in the transformation functions.

---

genesis/engine/entities/rigid_entity/rigid_entity.py

Update `inverse_kinematics_multilink` to allow `poss` and `quats` to contain `None` values, indicating that the respective property of the specified link is not considered in the IK calculation.

[FEATURE] Add link-wise mask for poss and quats in multilink IK

---

.gitattributes

When shell scripts have Windows style CRLF line endings, Unix systems may not recognize them as valid executible files. The core.autocrlf input setting tells Git to convert CRLF to LF, and keep LF as is. Fixes errors building dockers, and addresses the build_luisa.sh errors.

[BUG FIX] Add .gitattributes file for line endings handling

---

examples/rigid/domain_randomization.py
genesis/engine/entities/rigid_entity/rigid_entity.py

RigidEntiry set_mass_shift and set_COM_shift changed the function parameters link_indicies and we normally don't expect so.
create a temporary list instead so it does not affect the input parameters:
global_link_indices = [self._link_start + i for i in link_indices]
self._solver.set_links_COM_shift(com_shift, global_link_indices, envs_idx)

[Bug Fix] avoid changing input link index in rigid_entity

---

genesis/engine/scene.py

In `scene.py`, the description should be `renderer`, not `viewer_options`.

[MISC] fix minor typo in exception handling

---

examples/tutorials/advanced_hybrid_robot.py

Previously, `contact_resolve_time` was hardcoded to 0.02 but now it is set to None with default value as twice the `substep_dt` in the rigid solver. In hybrid robot setup, the `dt`'s of the rigid and the mpm solver are set to the same value to avoid drifting in coupling. However, this makes the `contact_resolve_time` becomes super small, leading to a stiff system and large impulse. Thus, we need to set the `contact_resolve_time` to a larger number (0.02) to fix the issue.
Related issue: https://github.com/Genesis-Embodied-AI/Genesis/issues/476

[Bugfix] unstable hybrid robot example

---

README.md

This is intended for Ubuntu OS. It is a fix for black screen due to X11 forwarding during rendering, it should provide a fix alsoo for ssh outlined in other issues: https://github.com/Genesis-Embodied-AI/Genesis/issues/33
/dev/dri mounting for ssh should be tested

Fix black screen

---

genesis/engine/entities/rigid_entity/rigid_entity.py

Fixed a typo in exception message at genesis/engine/entities/rigid_entity/rigid_entity.py

[MISC] Fixed a typo in exception message

---

examples/drone/README.md
examples/drone/hover_env.py
examples/drone/hover_eval.py
examples/drone/hover_train.py
genesis/engine/entities/drone_entity.py

**Changes:**
1. **Update drone_entity:**
- Converted data types from NumPy arrays to PyTorch tensors to improve performance.
- The `hover_train.py` script no longer requires using `tensor.cpu()` to transfer data from CUDA to CPU.
- In tests with parallel environments of 8192, 16384, 32768, and 65536, we observed an average training performance improvement of 20%.
2. **Adjust Hyperparameters:**
- Updated default hyperparameters to ensure more stable and higher reward training without affecting speed.
- Note: Further improvements in reward may require additional training time.
3. **Update README:**
- Added instructions for training with visualization.
---
Please review the changes and provide feedback. Thank you!

[MISC] Update Drone Entity and Training Performance Enhancements

---

examples/rigid/domain_randomization.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py

You can try
```
link = robot.get_link("RR_thigh")
rigid = scene.sim.rigid_solver
ori_mass = rigid.links_info.inertial_mass.to_numpy()
print("original mass", link.get_mass(), ori_mass)
link.set_mass(1)
new_mass = rigid.links_info.inertial_mass.to_numpy()
print("diff mass", new_mass - ori_mass)
```
in
```
python examples/rigid/domain_randomization.py
```

[BUG FIX] fix set mass

---

genesis/ext/pyrender/non_jit_renderer.py
genesis/ext/pyrender/viewer.py
genesis/vis/rasterizer_context.py
genesis/vis/viewer.py
genesis/vis/visualizer.py

This PR adds Windows compatibility to Genesis Viewer by providing a non-JIT implementation of the renderer.
The original Genesis Viewer uses JIT compilation for OpenGL rendering, which causes issues on Windows machines. This PR provides a non-JIT implementation while maintaining the same functionality.
- Implemented non-JIT renderer in `genesis/ext/pyrender/non_jit_renderer.py`
- Modified viewer implementation to support both JIT and non-JIT rendering
- Updated rasterizer context to handle the non-JIT renderer
- Kept the original JIT implementation intact for non-Windows environments
To test this implementation:
1. Install Genesis on a Windows machine
2. Run the viewer with a sample scene like: `python examples\rigid\control_franka.py --vis` or `python examples\rendering\moving_camera.py …

[FEATURE] Windows-compatible viewer support

---

examples/rigid/accelerometer_duck.py
examples/rigid/accelerometer_franka.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py

Add accelerometer by transforming com-based acceleration (`cdd_vel/ang`) with centrifugal correction. Not very positive if this is correct and thus making draft PR now (the duck example makes sense to me but not sure about the franka one). @YilingQiao  could you double check? Thanks
Related issue: https://github.com/Genesis-Embodied-AI/Genesis/issues/328
Demo script -- duck
```python
import time
import argparse
import numpy as np
def main():
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--vis", action="store_true", default=False)
args = parser.parse_args()
gs.init(backend=gs.gpu)
viewer_options = gs.options.ViewerOptions( …
```

[feature] add links acc (accelerometer)

---

genesis/__init__.py
genesis/utils/misc.py

Fixes https://github.com/Genesis-Embodied-AI/Genesis/issues/274 - Vulkan backend on non-cuda GPUs 
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/567 - Adds Pytorch 2.5+ Intel XPU support
Merges the logic of get_gpu_device() and get_cpu_device() to handle device selection in a single place.
If a specific backend is requested, this request is honored.
The vulkan backend will use intel's pytorch xps device if available, reducing cross-device data transfer.
The `gpu` backend will
- default to `cuda` when available,
- resolve to `mps` on macOS
- or fallback to `vulkan`.

[BUG FIX][FEATURE] Rework backend & device selection logic

---

genesis/ext/pyrender/trackball.py

This change initializes the `_pdown` instance variable of the `Trackball` object, which stores the x, y values of the initial mouse press for the camera drag in the viewer. It ensures `_pdown` is initialized to zeroes instead of `None`, preventing crashes in edge cases. Additionally, it removes the use of `getattr` to access `_pdown`, as it is always initialized.
No related existing issue.
Previously, viewer would crash if the `on_mouse_drag` callback was triggered before `on_mouse_click`. This happened because when the initial mouse press that should set `_pdown` attribute was missing, it had original value `None` from when the `Trackball` instance is created, resulting in a `TypeError` during camera drag calculations. This might happen in couple of edge cases, one way I am able to …

[BUG FIX] Mouse drag crashing the viewer in edge cases

---

examples/drone/interactive_drone.py
examples/locomotion/go2_env.py
examples/locomotion/go2_train.py
genesis/vis/camera.py
genesis/vis/viewer.py

Fixes #538 and #554 
Hello ! 
I made changes to the camera and viewer class so that they can now follow an entity in various ways.
For both the viewer and any camera, once they are created, you can : 
```python
sim_options=gs.options.SimOptions(dt=0.02, substeps=2),
viewer_options=gs.options.ViewerOptions(
max_FPS=50,
camera_pos=(2.0, 0.0, 2.5),
camera_lookat=(0.0, 0.0, 0.5),
camera_fov=40,
),
)
entity = scene.add_entity() #load any enity
scene.viewer.follow_entity(entity)
follower_camera = scene.add_camera(res=(640,480),
pos=(0.0, 2.0, 0.5),
lookat=(0.0, 0.0, 0.5),
fov=40,
GUI=True)
follower_camera.follow_entity(entity, fixed_axis=(None, None, 0.5), smoothing=0.5, fix_orientation=True)
```
In this code both the viewer and follower_camera will follow …

[FEATURE] Camera and viewer able to follow and entity

---

genesis/engine/entities/rigid_entity/rigid_entity.py

Changed `dofs_idx` to `dofs_idx_local` in `get_dofs_limit()` to match with other function
N/A

[BUG FIX] changed to dofs_idx_local of get_dofs_limit()

---

genesis/utils/mjcf.py

Replaced converting numpy array elements (`array.astype(int)`) with np.ceil operation (`np.ceil(array).astype(int)`). The reason I used this operation is [texrepeat values are positive](https://mujoco.readthedocs.io/en/stable/XMLreference.html#asset-material-texrepeat).
Resolves Genesis-Embodied-AI/Genesis#616
When mjcf texrepeat is handled, it is converted to integer. That causes some issues for values such as `[0.5, 0.5]` which is rounded down to `[0, 0]`. The zeros array ends up emptying the image_array at [307](https://github.com/Genesis-Embodied-AI/Genesis/blob/bae90367948d7ace52924c7442cc39aa81a15ec4/genesis/utils/mjcf.py#L307) and [341](https://github.com/Genesis-Embodied-AI/Genesis/blob/bae90367948d7ace52924c7442cc39aa81a15ec4/genesis/utils/mjcf.py#L341) of `utils/mjcf.py`.
This …

[BUG FIX] Update texrepeat handling for mjcf

---

examples/rigid/terrain_height_field.py
genesis/options/morphs.py
genesis/utils/terrain.py

Save terrain each time created from trimesh. IIt could be reused by assigning `name` and `from_stored` in morph.
None. But can extremely reduce the compile time.
Run `examples/rigid/terrain_height_field.py`

[FEATURE] save terrain and reuse by name

---

genesis/engine/solvers/rigid/support_field_decomp.py

Limit memory usage by using maximum window size 5e8 while computing supporting field.
Huge terrain may encounter ~100 GiB memory usage in this step.
- [ x] I read the **CONTRIBUTING** document.
- [ x] I followed the `Submitting Code Changes` section of **CONTRIBUTING** document.
- [ x] I tagged the title correctly (including BUG FIX/FEATURE/MISC/BREAKING)

[BUG FIX] limit memory usage in supportfield

---

genesis/vis/rasterizer_context.py
genesis/vis/visualizer.py

Although Offscreen (aka. headless) would work fine without 'RasterizerContext', it is not the case for onscreen rendering. As a result, printing a warning in case of import error within 'RasterizerContext' does not seem appropriate. Instead, it makes more sense to guard import of 'RasterizerContext' where it is actually needed, and trigger an exception if it fails. This way, the error will only be reported when necessary, and whole traceback will be printed.
Resolves Genesis-Embodied-AI/Genesis/issues/773
The warning is currently not clear: the root cause is not reported, and which feature is relying on it is not mentioned.
Since the error is triggered on my environment, all I had to do was running the tutorial to test whether it was fixing the issue.

[BUG] Better handling of rendering import failure.

---

genesis/ext/pyrender/jit_render.py
genesis/ext/pyrender/numba_gl_wrapper.py
genesis/vis/rasterizer_context.py

Add lazy-loading on OpenGL functions to postpone their initialisation after creation of the OpenGL context. This is necessary on Windows OS, where some functions depends on extensions that are not available until this point. This refactoring enables using the optimal code path for rendering on all Windows, Linux and MacOS. Ultimately, it should improve performance while being easier to maintain.
Resolves Genesis-Embodied-AI/Genesis#<your-issue-number> (TODO)
Running the tutorial on a native Windows x86 machine.
TODO: Check that it is still working on Mac OS.

[BUG] Improve rendering support on Windows OS.

---

genesis/ext/pyrender/renderer.py
genesis/ext/pyrender/viewer.py

Trying the resize the interactive window on Mac OS is causing segfault if shadows are enabled. The root cause is not clear, but systematically unbinding the frame buffer associated with the shadow map after use is sufficient to fix the issue. The overhead it induces is every minimal (< 10us) and only affects onscreen rendering, so it is not a big deal in the first place. Incidentally, enabling/disabling shadows is now working fine on Mac OS.
Triggering a segfault on Mac OS when trying to resize the interactive viewer is unacceptable. While it would be possible to disable resizable window on Mac OS, I do believe that being this feature is a common expectation.
Running the tutorial on my MacBook Pro M3 Max.

[BUG] Fix segfault when resizing window on Mac OS.

---

setup.py

Fix build fails for Python < 3.12 resulted by cython extensions that use numpy. After making genesis compatible with numpy 2.0, building failed for lower versions of Python.
Resolves Genesis-Embodied-AI/Genesis#788
In numpy>2.0, some C APIs (e.g. PyDataType_ELSIZE, PyDataType_FIELDS) are moved to new headers and required explicit setups (which wasn't required in numpy<2.0). Adding `include_dirs=[np.get_include()]` explicitly links to the updated numpy headers.
Source:
- [NumPy 2.0 migration guide](https://numpy.org/doc/stable/numpy_2_0_migration_guide.html)
- [Cython for NumPy users](https://cython.readthedocs.io/en/latest/src/userguide/numpy_tutorial.html#adding-numpy-headers)
1. have a clean python env (using venv, conda etc)
2. clone the branch
3. pip install -e .
edit 1: update …

[BUG] update setup.py to fix build fails

---

genesis/vis/visualizer.py

This PR fixes camera rendering state not being properly initialised on Windows OS, causing segfault. The same logic is now used whatever the OS when building the scene. It could be avoided on Mac OS, for which the viewer does not run in a background thread, but it does no harm either since the extra computation is only done once when building the scene.
Related to Genesis-Embodied-AI/Genesis/issues/466
Triggering a segfault on Windows OS when adding cameras to the scene is unacceptable.
Running the example script `examples/tutorials/visualization.py` on both Windows OS and Mac OS.

[BUG FIX] Fix cameras causing segfault on Windows OS.

---

genesis/vis/rasterizer.py
genesis/vis/visualizer.py

Enable headless rendering on Windows OS. Relying on `pyglet` instead of `egl` because efficiency only really matters on Linux, and EGL is not working out-of-the-box on Windows OS. This limitation could be addressed in a subsequent PR.
Resolves Genesis-Embodied-AI/Genesis/issues/466
Headless rendering is currently disabled on Windows because many other features it requires to work properly were previously broken. It is not straightforward to enable it back.
Running the example script `examples/tutorials/visualization.py` on both Windows OS and Mac OS, tweaked with `show_viewer=False` and `GUI=False`.

[FEATURE] Add support on headless rendering on Windows OS.

---

genesis/vis/rasterizer.py
genesis/vis/viewer.py
genesis/vis/visualizer.py

This PR removes all the logic related to partially supported rendering capability depending on the platform, which is not relevant anymore. If rendering is not working, then it is coming from the user-side, not Genesis. For this reason, importing `pyrender` no longer fails silently but rather raises an exception containing the full backtrace to help the user debugs its setup.
Resolves Genesis-Embodied-AI/Genesis/issues/26
Let us get rid of the special logic to deal with unsupported offscreen rendering since now it works on any platform. This makes the codebase easier to maintain and ensures that the feature set is consistent across platforms. Now it is binary: either rendering is completely broken and no features can be used at all (which is a bug on the user-side, not genesis), or all of …

[BUG FIX] Better handling of rendering import failure (cont'd).

---

genesis/vis/visualizer.py
pyproject.toml

This PR replaces `screeninfo` by `pyglet` to get the physical screen resolution.
The screen resolution is not properly detected by `screeninfo` on High-DPI and Mac Retina display. Anyway, relying on `screeninfo` can be avoided in the first place since `pyglet` is already part of the requirements (dragged by Pyrender, which is not going anywhere soon). 
Running the tutorial on my MacBook Pro M3 Max.

[BUG FIX] Fix screen resolution detection for high-DPI display.

---

genesis/engine/entities/rigid_entity/rigid_geom.py
genesis/engine/mesh.py
genesis/utils/element.py
genesis/utils/mesh.py
genesis/utils/particle.py

Ignore cached data if they are corrupted and regenerate them automatically. Use context manager systematically to handle file read/write, with is important to make sure that the file content is properly flushed on hard drive, thereby reducing the likelihood of data corruption.
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/98
Finding out that the error is related to cache corruption is already tricky, but the user also has to identify where the corresponding file is located on its computer in order to delete it manually. It would be much better to automate this process.
Writing non-sense in one of the cache file generated in the tutorial, e.g. `$HOME/.cache/genesis/gsd/*.gsd`  on Mac OS.

[BUG FIX] Robust caching mechanism.

---

genesis/ext/pyrender/platforms/egl.py
genesis/ext/pyrender/platforms/pyglet_platform.py
genesis/ext/pyrender/viewer.py

Change the default EGL device selection method, to go through all the available devices and stick to the first one that works.
Related to Genesis-Embodied-AI/Genesis/issues/43
Currently, the "first" available EGL device is being used by default if none has been specified. This is problematic has it may not be the one reported as being the "default" by EGL itself (i.e. `EGL_DEFAULT_DISPLAY`), and it may not be working at all. It would be better to go through all the available devices and stick to the first one that is actually working.
Running the example script `examples/tutorials/visualization.py` on both Ubuntu 24.04 via WSL2 on Windows OS, tweaked with `show_viewer=False`.

[BUG FIX] Fix EGL device detection.

---

pyproject.toml

Increase the minimum version requirement for `pyglet`.
Resolves Genesis-Embodied-AI/Genesis/issues/803
`pyglet` has introduced breaking API changes since 2.1. While it would be possible to support both the new and old release by trying both APIs, I do not think it is worth it since this package is Python-only anyway, so it can be installed on any platform without issue.
Running the tutorial on my machine.

[BUG FIX] Bump pyglet version requirement due to breaking API changes.

---

genesis/ext/pyrender/offscreen.py
genesis/ext/pyrender/platforms/egl.py

This PR relies on the newly introduced "robust" EGL device detection logic to choose the right device if none has been specified by the end-user, instead of forcing the device "0" in such a case.
Resolves Genesis-Embodied-AI/Genesis/issues/648
Resolves Genesis-Embodied-AI/Genesis/issues/281
Resolves Genesis-Embodied-AI/Genesis/issues/521
The EGL device "0" is systematically preferred even if non has been specified by the end-user. This is problematic has it may not even exist, which would raise an exception.
Running the example script `examples/tutorials/visualization.py` for both onscreen rendering (`show_viewer=False`, `GUI=False`) and offscreen rendering (`show_viewer=True`, `GUI=True`) on several platforms:
* Ubuntu 24.04 via WSL2 on Windows OS (Intel x86 + Nvidia GPU Quadro)
* Native …

[BUG FIX] Rely on automatic EGL device detection if not specified.

---

genesis/engine/entities/tool_entity/mesh.py
genesis/ext/fast_simplification/simplify.py
genesis/ext/pyrender/jit_render.py
genesis/ext/pyrender/non_jit_renderer.py
genesis/ext/pyrender/primitive.py
genesis/ext/pyrender/texture.py
genesis/ext/pyrender/utils.py
genesis/ext/trimesh/geometry.py
genesis/ext/trimesh/grouping.py
genesis/ext/trimesh/transformations.py
genesis/ext/trimesh/voxel/runlength.py
genesis/vis/rasterizer_context.py

This PR fixes compatibility issues with numpy 2.X. Besides, flattening and data type casting has been refactored to avoid unnecessary copies whenever possible, and limit them to a single one per operation otherwise. Before this PR, flattening was systematically copied the original data (because it is what `flatten` does). Same for `astype()` without passing the optional argument `copy=False`. As a result, the original data was systematically copied twice if both flattened and casted were performed. 
Resolves Genesis-Embodied-AI/Genesis/issues/789
Numpy 2.X introduces breaking changes. The codebase needs to be updated accordingly to support Numpy 2.X without breaking backward compatibility. Among the notable changes:
* Type promotion logic has changed and is now strict. In particular, …

[BUG FIX] Avoid unnecessary array copies and improve support of Numpy 2.X.

---

genesis/ext/pyrender/jit_render.py

fix for IS_OPENGL_42_AVAILABLE condition.
current method raised error for tiled rendering even with OpenGL >= 4.2 is installed

[BUGFIX] IS_OPENGL_42_AVAILABLE condition bug

---

genesis/ext/pyrender/jit_render.py

Avoid relying on private API `build_wrapper` and `gl_funcs` to detect OpenGL version. These are implementation details that may change at any point in time. Only `wrapper_type` and `wrapper_instance` are public API.
Related to Genesis-Embodied-AI/Genesis/pull/813
Even though the current implementation is working. Relying on private API is a bad practice and must be avoided.
Testing locally on my machine the condition check for both `glDrawElementsInstancedBaseInstance` and `glUniformMatrix4fv`.

[BUG FIX] Update OpenGL 4.2 detection to stick on Public API.

---

genesis/engine/solvers/rigid/rigid_solver_decomp.py

Fix #817 
There are two bugs.
1. should use `verts_state_idx` instead of `i_v` in _func_update_verts_for_geom
2. should not +1 when using np.arange
Resolves #817 
Could use the test examples in #817

[BUG FIX] fix verts_state_idx

---

examples/tutorials/IK_motion_planning_grasp.py
genesis/engine/scene.py
genesis/vis/rasterizer_context.py

Enable visualizing a path for rigid entities using FK.
Opening this PR to improve the convenience of visualizing a path.
I have modified `examples/tutorials/IK_motion_planning_grasp.py` to visualize the path. The example script can be used to test. (If requested, I can add a separate example script to demonstrate this feature.)

[FEATURE] Enable visualizing path

---

genesis/__init__.py
genesis/logging/logger.py
genesis/utils/mjcf.py

* Silence OpenGL dynamics library loading between Taichi and Mujoco Viewer on MacOS, that should be harmless but very confusing for the end-user, especially when an actually bug happens latter. 
* Prefer CPU over GPU in debug mode, and Apple Silicon machines as Metal support is partially broken. 
* Fix high-precision computation that was only partially enforced.
* Use deterministic algorithms and disable parallel computations in Debug mode
* Always disable Taichi debug mode on Apple Silicon with CPU backend as it causes segfault
Related to Genesis-Embodied-AI/Genesis/issues/555
Related to Genesis-Embodied-AI/Genesis/issues/368
Related to Genesis-Embodied-AI/Genesis/issues/165
Related to Genesis-Embodied-AI/Genesis/issues/32

[BUG FIX] Improve debug and high-precision mode.

---

genesis/engine/solvers/rigid/constraint_solver_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp_island.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py

This PR fixes gradient and improvement scaling.
Gradient and improvement scaling are used in Mujoco as a way to improve the numerical stability of the constraint solver. More specifically, the tolerance involved in the termination condition of the iterative solver is scaled by the mean inertia matrix of each entity, so that the condition gets more or less restrictive depending on the mass of each entity. Implementing this regularisation is necessary to match Mujoco.

[BUG FIX] Fix constraint solver termination condition.

---

.github/workflows/ci.yml
examples/rigid/set_phys_attr.py
genesis/__init__.py
genesis/assets/xml/walker.xml
genesis/constants.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_joint.py
genesis/engine/entities/rigid_entity/rigid_link.py
genesis/engine/solvers/rigid/constraint_solver_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp_island.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/options/solvers.py
genesis/utils/mjcf.py
genesis/utils/urdf.py
pyproject.toml
tests/conftest.py
tests/test_rigid_physics.py
tests/utils.py

This PR gets rid of joint fusing completely in order to keep the original joint composition. First, this was confusing end-user that were trying to access data related to the original joints for their application. Second, it was impossible to support specifying different joint pose, as they cannot be fixed into one time-independent joint.
Related to Genesis-Embodied-AI/Genesis/issues/461
Resolves Genesis-Embodied-AI/Genesis/issues/762
Supersedes Genesis-Embodied-AI/Genesis/pull/792
Resolves Genesis-Embodied-AI/Genesis/discussions/837
Chaining multiple basic 1DoF joints is the standard approach in Mujoco for implementing complex N-DoF joints, including spherical joints. Currently, only chaining multiple DoFs is supported in Genesis, which is not the same as chaining multiple joints as it …

[FEATURE] Add support of compound joints

---

examples/render_async.py
genesis/__init__.py
genesis/engine/scene.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/ext/pyrender/viewer.py
genesis/options/vis.py
genesis/vis/viewer.py
genesis/vis/visualizer.py
pyproject.toml

This PR fixes several issues:
* compilation on Apple Metal. 
* silencing on libc stderr at import that was breaking Taichi tracing even after restoring pipe
* black formatter running on external dependencies
This PR adds an option to force disabling running the viewer on a background thread, and provides an example that maintains maximum performance on all platforms.
Running franka tutorial on Apple Silicon machine with Metal backend enabled.

[FEATURE] Give user the ability to choose whether to run viewer in thread.

---

genesis/__init__.py
genesis/utils/misc.py
genesis/utils/mjcf.py
tests/conftest.py

This PR parses the group field of geometries to decide whether or not a visual geometry should be added for a given collision geometry.
Resolves Genesis-Embodied-AI/Genesis/issues/140
Related to Genesis-Embodied-AI/Genesis/issues/205
Currently, collision meshes are not rendered by default, unless there is no visual geometry associated with a given body. This is not enough to replicate the behaviour of Mujoco. It is also necessary to take into account the visual group of each geometry (1 and 2 are rendered by default).
Load metaworld 'sawyer_pick_place_v2.xml' asset as described in the issue, along the existing franka and ur5e assets.

[BUG FIX] Improve loading of MJCF visual meshes.

---

genesis/ext/pyrender/viewer.py

This PR fixes handling of cancelled dialog when asked to choose a file path for saving pictures or videos of the viewer. When it happens, nothing is saved and simulation resumes flawlessly instead of picking some random default location. I think this behaviour is closer to what the user would expect.
Supersedes Genesis-Embodied-AI/Genesis/pull/834
Currently, when saving pictures and videos of the viewer, closing the file dialog without closing any file crashes the viewer, which is not acceptable.
Running Franka tutorial on my machine with viewer enabled and trying the save pictures and videos.

[BUG FIX] Fix viewer crash when canceling save dialog.

---

genesis/__init__.py
genesis/engine/entities/rigid_entity/rigid_entity.py

This PR looks for the site packages directories first when failing to import OMPL dynamic libraries, and only fallbacks to system libraries if it does not works. Raises an exception if not found, which was not the case previously.
Resolves Genesis-Embodied-AI/Genesis/issues/366
Resolves Genesis-Embodied-AI/Genesis/issues/401
Resolves Genesis-Embodied-AI/Genesis/issues/318
Related to Genesis-Embodied-AI/Genesis/issues/505
Related to Genesis-Embodied-AI/Genesis/issues/749 
Currently, the import logics of OMPL dynamics shared libraries is quite fragile and causes segfault if a different version is already installed on the system. Fixing this issue is important because it would be too difficult to debug for the average user. This bug has been reported [ompl …

[BUG FIX] Fix fragile libompl dynamic library import logics.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/utils/misc.py
pyproject.toml
tests/test_rigid_physics.py

This PR refactors all the data accessors related to the Rigid Body solver to directly copy the original data buffer, removing any unnecessary level of indirection. At this point, it does not implement any other optimisation than adding an 'unsafe' mode that disable runtime checks. The next step would be to add some optional 'out' and 'non_blocking' arguments in a torch-like fashion to avoid dynamic memory allocation and implicit synchronisation points altogether.
Currently, data accessors are taking a big part of the whole computation time, for several reasons. First, memory is systematically preallocated. Seconds, there are many runtime checks that are done systematically while they are only necessary for the first simulation step in RL applications. Finally, all operations are blocking, …

[MISC] Refactor rigid body data accessors.

---

genesis/utils/mjcf.py

This PR restores the original behaviour from before https://github.com/Genesis-Embodied-AI/Genesis/pull/870 for joints whose attached actuator cannot be parsed. In this case, default PD controller gains are used instead of setting them to zeros. In the particular case where there is a mismatch between position gain associated with target and measured position, the maximum value between them is used instead of the default value. Moreover, tendons are now parsed to determine if an actuator is directly or indirectly attached to a joint. More warnings are printed to make sure that the user is aware of the aforementioned discrepancy when they occur.
Resolves https://github.com/Genesis-Embodied-AI/Genesis/discussions/927
Since https://github.com/Genesis-Embodied-AI/Genesis/pull/870, if no …

[BUG FIX] Add fallback when failing to parse actuators from MJCF file.

---

README.md
README_FR.md
README_JA.md
README_KR.md

Clarify in README how to install the latest version of Genesis and which version of Python is supported.
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/930
Currently, the proposed approach to install the latest version is not the best one, and breaks if the user already installed the version available on PyPI.
Just fallowing the README should be fine!

[MISC] Update install procedure on README.

---

examples/rigid/terrain_subterrain.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/mesh.py
genesis/utils/mesh.py
genesis/utils/terrain.py
tests/test_rigid_physics.py

This PR stops relying on high-level trimesh API `simplify_quadric_decimation` to call directly Genesis internally managed version of `fast_simplification`. Moreover, it fixes the API changes `_add_by_info` in `_load_terrain`. Finally, a unit test has been added to make sure this issue does not happen again.
Resolves Genesis-Embodied-AI/Genesis/issues/944
Terrain support is currently broken. First, because of the implementation of compound joints that changed the API of `_add_by_info`. Second, because trimesh is no longer internally managed, and the internal API for `simplify_quadric_decimation` has not been backported as it should. 
Adding a unit test based on `examples/rigid/terrain_subterrain.py` example.

[BUG FIX] Fix terrain support.

---

genesis/engine/solvers/rigid/rigid_solver_decomp.py

This PR adds a checks to make sure that a link has some dofs before trying to access its child joints.
Fixed joints are now removed when parsing MJCF files for consistency with Mujoco. Because of this, some links having fixed joint as direct child are now joint-less. Because of this, checking the type of the child joint in Rigid Body Dynamics computations causes out-of-bounds memory access. Ideally it crashes, but it can also do crazy stuffs...

[BUG FIX] Fix fixed joint support.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/mesh.py
genesis/engine/scene.py
genesis/engine/solvers/rigid/mpr_decomp.py
genesis/options/misc.py
genesis/options/morphs.py
genesis/utils/mesh.py
genesis/utils/mjcf.py
genesis/utils/terrain.py
tests/test_rigid_physics.py

* Support mesh post-processing for all file morphs.
* Improve convexify VS decompose switch logics. 
* Enable back convexify by default.
* Add convex collision detection unit test.
Resolves  Genesis-Embodied-AI/Genesis/issues/614
Resolves Genesis-Embodied-AI/Genesis/issues/951
Related to Genesis-Embodied-AI/Genesis/issues/602

[FEATURE] Enable back convexify by default.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/utils/misc.py

This PR improves the performance of utility to convert taichi field to torch by implementing a specialised CPP-to-Python interface and relying on caching mechanisms to access field shape, dtype and kernel key.
Because of its versatility, taichi is not good at executing very small kernels, such as the one responsible for converting data from taichi to PyTorch. This makes data accessor are fairly slow, which is a problem for RL applications. It should be possible to make data accessor faster implementing a low-level interface optimised for data-accessors.

[MISC] Speed-up convert taichi field to torch.

---

examples/rigid/convex_decomposition.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/options/morphs.py
genesis/utils/mesh.py
genesis/utils/mjcf.py
tests/test_rigid_physics.py

Check if each geometry can be convexified independently without resorting on convex decomposition. If so, the original geometries are preserve. If not, then they are all merged as one. The resulting geometry is convexify without resorting on convex decomposition if possible. 
Several collision meshes may be attached to a single body. This is fine as long as there is no need to rely on convex decomposition. Otherwise, the final number of collision geometries may be very large, typically more than 50. These  impedes runtime performance, numerical stability and compilation time, without significant benefit. It would be much better to merge all the meshes before applying convex decomposition. It also gives one last opportunity to check whether the convex hull of the merged mesh is accurate …

[FEATURE] Merge meshes before convex decomposition.

---

examples/rigid/convex_decomposition.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/mesh.py
genesis/engine/scene.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/mpr_decomp.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/options/morphs.py
genesis/options/solvers.py
genesis/options/surfaces.py
genesis/utils/mesh.py
tests/conftest.py
tests/test_rigid_physics.py

* Apply morph pose as transform wrt original base pose
* Randomize collision mesh colors
* More challenging convex decomposition example / unit test
* Enable decimation by default if convexify is enabled. 
* Do not decimate before convex decomposition.
* Reduce MPR epsilon threshold (basically disable it for float32) to avoid jerky contact points 
* Enforce option constraint time constant systematically if and if specified.
Resolves Genesis-Embodied-AI/Genesis/issues/751

[BUG FIX] Improve numerical stability of collision detection

---

genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/mpr_decomp.py
genesis/vis/rasterizer_context.py
tests/conftest.py
tests/test_rigid_physics.py

* Add support of analytically ellipsoid shape for collision detection
* Do not disable multi-point collision detection for self-collision
* I see no reason for doing this, and Mujoco does not do it either 
* Add first-order penetration depth correction term for multi-point collision detection
* This is important to avoid spurious / jerky motion
* Increase CCD epsilon threshold now that collisions are more stable
Improve the numerical stability of the simulation for contact-heavy scenes is very important for learning dexterous manipulation tasks.

[BUG FIX] Improve multi-point contact stability

---

examples/locomotion/go2_backflip.py
examples/locomotion/go2_env.py
examples/locomotion/go2_eval.py
examples/locomotion/go2_train.py

This PR fixes code compatible bug with the latest version of RL library, `rsl-rl-lib==2.2.4`.
- The latest `rsl-rl-lib` gets `obs` and `extras` as the return of `get_observation()` function. However, the previous code returns only `obs` variable. 
```
Traceback (most recent call last):
File "G:\Genesis_local\examples\locomotion\go2_train.py", line 170, in <module>
main()
File "G:\Genesis_local\examples\locomotion\go2_train.py", line 159, in main
runner = OnPolicyRunner(env, train_cfg, log_dir, device="cuda:0")
File "C:\Users\Admin\.conda\envs\Genesis\lib\site-packages\rsl_rl\runners\on_policy_runner.py", line 32, in __init__
obs, extras = self.env.get_observations()
ValueError: too many values to unpack (expected 2)
Process finished with exit code 1
```
I changed below code to make …

[BUG FIX] go2 locomotion code compatible with `rsl-rl-lib==2.2.4`

---

genesis/engine/entities/rigid_entity/rigid_entity.py
tests/test_rigid_physics.py

This PR fixes base robot pose overwrite for MJCF morph files.
Resolves Genesis-Embodied-AI/Genesis/issues/987
Adding a new unit tests making sure it works fine.

[BUG FIX] Fix MJCF overwrite robot pose.

---

examples/rigid/apply_external_force_torque.py

When running the apply external force/torque example, the script fails with following errors.
```
Traceback (most recent call last):
File "/home/alexis/Documents/python/robotics/Genesis/examples/rigid/apply_external_force_torque.py", line 78, in <module>
main()
File "/home/alexis/Documents/python/robotics/Genesis/examples/rigid/apply_external_force_torque.py", line 55, in main
cube_pos = rigid_solver.get_links_pos(link_idx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/alexis/Documents/python/robotics/Genesis/genesis/engine/solvers/rigid/rigid_solver_decomp.py", line 4359, in get_links_pos
tensor = ti_field_to_torch(self.links_state.pos, envs_idx, links_idx, transpose=True, unsafe=unsafe)
^^^^^^^^^^^^^^^^
File "/home/alexis/Documents/python/robotics/Genesis/.venv/lib/python3.11/site-pac …
```

[BUG FIX] Fix dimension error while running apply external force/torque example

---

genesis/engine/mesh.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/utils/mesh.py
genesis/utils/mjcf.py
tests/test_rigid_physics.py

This PR disables multi-point contact for pairs of decomposed geometries by default. The existing 'enable_multi_contact' rigid option has been generalised to be 3-states ("auto", enabled, disabled). 
Multi-point collision is kind of redundant with convex decomposition. Doing both at the same time would significantly increase the potential number of contact points, which may dramatically slowdown simulation. Ultimately, this would lead to unfair benchmark against other simulators. As a result, multi-point contact should be disabled by default in this case.

[FEATURE] Disable multi-point contact for pairs of decomposed geometries

---

.github/workflows/ci.yml
docker/Dockerfile
genesis/__init__.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
pyproject.toml
tests/conftest.py
tests/test_rigid_benchmarks.py
tests/test_rigid_physics.py

* Disable self collision on Franka for large-scale benchmarks as it causes CUDA OOM issues
* Make it possible again to set the pose of a robot having a fixed base link
* Install pre-compiled binary wheels of OMPL available on PyPI
* ~~orce running unit tests in isolated subprocesses. I tried to reduce the amount of RAM being reserved for each worker from 4GB to 3GB but takes up to 95% of the available RAM. Reverting to avoid instability since the CI is a shared machine.~~ (It turnout it is not possible to do this systematically because forking cannot be used due GPU devices limitations (and is not even available on Windows OS) and spawn cannot be used because of pytest fixture limitations...)
As the number of unit tests increasing, addressing the memory leak issue of Genesis (see …

[BUG FIX] Fix CI Out-Of-Memory issues.

---

genesis/engine/entities/rigid_entity/rigid_geom.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/mpr_decomp.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
tests/conftest.py
tests/test_rigid_physics.py

* Fix broken 'qf_passive' for non-zero damping.
* Add first-order perturbation compensation of contact normal.
* More robust computation of perturbation axes for multi-point contact.
* Do not disable multi-point contact for pairs of decomposed geometries.
* Increase multi-contact repeated point tolerance.
* Add unit test for collision edge cases.
* Tune unit tests for flakyness.

[BUG FIX] More robust computation of perturbation axes for multi-point contact.

---

genesis/utils/misc.py

This PR allows using Vulkan backend for taichi while using CPU for torch.
Resolves Genesis-Embodied-AI/Genesis/issues/1024
It would be great if someone could test this...

[BUG FIX] Using Vulkan backend for taichi even if no Intel XPU device is available

---

genesis/utils/mesh.py
tests/test_rigid_physics.py

This PR considers that the ratio between the original volume and its convex decomposition is infinity.
Resolves Genesis-Embodied-AI/Genesis/issues/1015
Partially broken meshes with flipped faces are not considered watertight. Because of this, their volume is not properly computed and they are never composed. If convexify is enabled, their convex hull will be used for collision, while convex decomposition was eventually necessary in the first place. The only option left to the user is to completely disable convexify. However, SDF collision detection is fragile, and having flipped vertices is not going to help... I suggest to always apply convex decomposition to meshes that are not watertight, unless this option is completely disabled via `decompose_error_threshold'=float('inf')`.
Running …

[BUG FIX] Improve support of partially 'broken' mesh.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_geom.py
genesis/engine/mesh.py
genesis/options/morphs.py
genesis/utils/mesh.py

This PR exposes 'decimate_aggressiveness' parameter and use it to enable decimation systematically. By default, aggressiveness is set to lossless if convexify is disabled, 2 otherwise.
Related to Genesis-Embodied-AI/Genesis/issues/1015
Enable decimation systematically would improve simulation speed and probably improve numerical stability and physical stability. If convexify is disabled, then decimation should be set to lossless mode instead of being completely disabled by default.

[BUG FIX] Expose decimate aggressiveness option.

---

genesis/options/morphs.py
genesis/utils/mjcf.py
genesis/utils/urdf.py
genesis/vis/rasterizer.py
genesis/vis/rasterizer_context.py
genesis/vis/visualizer.py
tests/test_rigid_physics.py

This PR fixes scaling factor wrongly applied to joint equality data, missing scaling factor for bounds of prismatic joints, and missing scaling factor for the translational part of the initial configuration vector `qpos0`. Besides, the PD controller gains are also scaled based on a simple heuristics that is not ideal but better than nothing.
Resolves Genesis-Embodied-AI/Genesis/discussions/1001
Robot scaling is currently partially broken and must be fixed.
Adding a unit test.

[BUG FIX] Fix robot scaling.

---

.github/workflows/ci.yml
genesis/utils/misc.py
tests/conftest.py
tests/test_rigid_benchmarks.py
tests/test_rigid_physics.py

This PR enables torch CUDA for taichi Vulkan backend.
Resolves Genesis-Embodied-AI/Genesis/issues/1024
Related to Genesis-Embodied-AI/Genesis/issues/1042
AMD GPUs are supported by PyTorch as CUDA devices via ROCm. Enabling this on Genesis would (hopefully) speeds up simulations for machines using AMD GPUs. 
Running the unit tests with `--backend vulkan` on AMD GPU machine.

[FEATURE] Use torch cuda with vulkan taichi backend if available.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/scene.py
genesis/options/morphs.py
genesis/utils/mesh.py

This PR exposes different convex decomposition error thresholds for robots and objects.
Resolves Genesis-Embodied-AI/Genesis/issues/1055
Convex decomposition is very important for rigid objects that are part of the scene, especially for manipulation tasks. However, it is usually necessary for robots because the non-physical part that is added to the original geometries to convexify them are generally inside the mechanical structure and therefore are not interacting directly with the outer world. Since convex decomposition is not free of cost (it increases the memory footprint, the compilation time, the simulation speed to some extent), it would be better to disable it by default for robots.
Running the unit tests and checking whether robots / objects were convexified.

[FEATURE] Expose different convex decomposition error thresholds for robots and objects.

---

genesis/_main.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_link.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
tests/conftest.py
tests/utils.py

Revert nested list data structure (list of direct child joints associated with each link) for storing joints introduced by compound joints PR https://github.com/Genesis-Embodied-AI/Genesis/pull/853 in favour of a flattened list of all the joints for a given entity. Adding getter `RigidEntity.joints_by_links` for users that would be interested in the nested hierarchy. 
This newly introduced nested list data structure for storing joints (list of direct child joints associated with each link) that was introduced by compound joints PR https://github.com/Genesis-Embodied-AI/Genesis/pull/853 is breaking backward compatibility, and is confusing for some. It would be better to revert this change at user-API level, plus add another getter to access the hierarchical representation.
Running the unit …

[MISC] Get rid of recently introduced nested joints data structure.

---

examples/locomotion/go2_backflip.py
examples/locomotion/go2_env.py
examples/locomotion/go2_train.py
examples/rigid/accelerometer_duck.py
examples/rigid/accelerometer_franka.py
examples/rigid/control_franka.py
examples/rigid/control_mesh.py
examples/rigid/domain_randomization.py
examples/rigid/ik_custom_chain.py
examples/rigid/merge_entities.py
examples/rigid/set_phys_attr.py
examples/speed_benchmark/anymal_c.py
examples/tutorials/control_your_robot.py
genesis/_main.py
genesis/assets/urdf/shadow_hand/shadow_hand.urdf
genesis/engine/entities/drone_entity.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_joint.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/options/morphs.py
genesis/options/solvers.py
genesis/options/vis.py
tests/test_rigid_benchmarks.py
tests/utils.py

This PR fixes a few naming conventions issue: 
I tried to infer a good naming convention from the actual codebase and I ended up with the following **rules for variable names**.
For individual instances:
* Snake case: `link_idx` vs `LinkIdx`
* No abbreviation: prefer `joint_` vs `jnt_` / `link_` vs `ln_` 
* Notable exception (for now): `idx` vs `index`, `n` vs `num`
For containers holding multiple instances: 
* First word is the parent type, followed by the child attribute: `links_dof_start` vs `dof_start_links`
* `s` suffix on the first word only (even if grammatically wrong): `links_name` vs `link_names`
OR 
* type of container as last word: `_pair`, `_set`, `_map`, `_list`
For nested containers:
* Order word from highest to lowest hierarchical level
* As many `s` suffixes or container …

[MISC] Fix naming convention inconsistencies.

---

genesis/__init__.py
genesis/ext/pyrender/offscreen.py
genesis/ext/pyrender/renderer.py
genesis/ext/pyrender/viewer.py
genesis/vis/rasterizer.py
tests/test_rigid_physics.py

* Enforce clearing of OpenGL frame buffer between (RGB + Depth Map) vs Normal Map
* Gather (RGB + Depth Map) rendering pass with Normal Map
* Unify logics between onscreen and offscreen rendering
Resolves Genesis-Embodied-AI/Genesis/issues/546
Currently, the viewer is facing 2 different issues. First, it is non-deterministic: A given scene may produce different RGB arrays despite being in the exact same physical state. The difference is only +/- 1 (on 0 to 255 uint8 scale). This is messing up with unit tests checking reproducibility of the simulation as a whole. Second, the segmentation map has graphical glitches when normal map is also enabled. This is more problematic has it means it cannot be used reliably practical user applications (training agents or anything else).
Running the unit …

[BUG FIX] Fix rendering bugs (non-deterministic, segmentation map glitches).

---

examples/rigid/terrain_from_mesh.py
genesis/assets/meshes/terrain_45.obj
genesis/utils/terrain.py
pyproject.toml
tests/test_rigid_physics.py

Sometimes user might want to import a non-convex terrain represented by a mesh. The best practice is to convert that mesh to a height field for more accurate collision detection. 
A function based on ray-casting is added for this purpose.
Try 
```bash
python examples/rigid/terrain_from_mesh.py -v
```
Resolves Genesis-Embodied-AI/Genesis/issues/790 
Resolves Genesis-Embodied-AI/Genesis/issues/491 
Related to Genesis-Embodied-AI/Genesis/issues/690 
Related to Genesis-Embodied-AI/Genesis/issues/625

[FEATURE] Add a function to convert terrain mesh to height field

---

genesis/assets/xml/one_ball_joint.xml
genesis/engine/solvers/rigid/rigid_solver_decomp.py
tests/test_rigid_physics.py

`qpos` for ball joint is represented by quaternion. Fix the time integration accordingly.
Try
```
pytest --pdb -v --vis tests/test_rigid_physics.py::test_one_ball_joint
```

[BUG FIX] Fix time integration for ball joint

---

genesis/engine/entities/fem_entity.py
genesis/engine/entities/pbd_entity.py
genesis/engine/mesh.py
genesis/options/morphs.py
genesis/utils/mesh.py
tests/conftest.py
tests/test_fem.py
tests/test_pbd.py

This PR introduces a `maxvolume` option that lets users cap the maximum tetrahedron volume generated by TetGen.
While adding this feature, the TetGen pipeline was refactored as follows:
* **Using switch string** – A new `utils.mesh.make_tetgen_switches()` helper was introduced to convert a config dict into the canonical TetGen switch string. This addresses an issue where the existing TetGen wrapper could silently ignore options like `maxvolume`.
* **Entity simplification** – Previously, FEM and PBD entities had separate implementations for generating TetGen configurations from a morph instance. These were unified to use a single helper (`utils.mesh.generate_tetgen_config_from_morph`), making behaviour consistent across solvers.
* **Public API change (BREAKING)** – `Mesh.tetrahedralize()` …

[FEATURE][BREAKING] Add maxvolume support for TetGen-based tetrahedralization, unify TetGen config handling, and add tests

---

.github/workflows/Dockerfile
.github/workflows/setup_env.sh
examples/rigid/convex_decomposition.py
genesis/__init__.py
genesis/_main.py
genesis/assets/xml/one_ball_joint.xml
genesis/engine/entities/rigid_entity/rigid_link.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp_island.py
genesis/engine/solvers/rigid/mpr_decomp.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/engine/solvers/sph_solver.py
genesis/options/solvers.py
genesis/utils/bvh.py
genesis/utils/geom.py
genesis/utils/mesh.py
genesis/utils/mjcf.py
genesis/utils/urdf.py
genesis/vis/rasterizer_context.py
genesis/vis/visualizer.py
tests/conftest.py
tests/test_rigid_physics.py
tests/utils.py

* Add support to rotational invweight0, which is involved in weld constraint.
* Fix compilation on MacOS.
* Fix 'draw_contact_arrow' method ignoring user-specified color.
* Replace mass matrix LU factorization by LTDL and use linear system solving instead of explicit matrix inversion.
* Fix constraint solver search vector norm computation.
* Fix handling of first-order correction terms related to implicit integration.
* Add Mujoco compatibility mode for unit test and debugging purposes.
Being able to match mujoco results as closely as possible is important to make sure that Genesis' implementation is valid without having to write a myriade of unit tests.
Running all the unit tests successfully.

[BUG FIX] Fix mujoco vs genesis discrepancies.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/options/solvers.py
genesis/utils/mesh.py
genesis/utils/mjcf.py
pyproject.toml
tests/test_rigid_physics.py

* More robust mesh post-processing.
* Add support of explicit excluded collision pairs in MJCF files.
* Fix detection of whether a link is part of a robot for convex decomposition.
* More robust joint name extraction from Mujoco.
* Update default rigid options to match Mujoco.
Complex MJCF scenes may not be properly loaded, either because convex decomposition is triggered when it should not, or because collision pairs that are explicitly blacklisted by the user are still taken into account in Genesis. There is an issue with the extraction of the joint names that may be failing from time to time, along with spurious confusing logging messages that are not appropriate.
Here are examples of scene that are not loading properly because this patch:
* mujoco_menagerie/aloha/scene.xml
* …

[BUG FIX] More robust robot loading and default options.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/utils/mjcf.py
genesis/utils/urdf.py
tests/test_rigid_physics.py

This PR replaces equality constraint object indices (either joint or link depending on constraint type) by names at parser-level. Mapping from names to indices is moved at RigidEntity-level. 
Resolves Genesis-Embodied-AI/Genesis/issues/1143
Equality constraints are holding "references" to the "objects" they are affecting, e.g. bodies, joints, tendons...etc Currently, these references are the indices in RigidEntity data structure. This is problematic, because the actual data structure is not available when parsing robot description files (URDF, MJCF), which means that it is necessary to reverse-engineering RigidEntity within the parsers to guess what should be the right indices. This is problematic because it is error-prone. Ideally, the parser can be order independent and therefore …

[BUG FIX] More robust equality parsing. Refactor MJCF parsing.

---

examples/rigid/grasp_bottle.py
genesis/__init__.py
genesis/engine/entities/drone_entity.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_geom.py
genesis/engine/scene.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/logging/logger.py
genesis/options/morphs.py
genesis/utils/mesh.py
genesis/utils/misc.py
genesis/utils/mjcf.py
genesis/utils/particle.py
genesis/utils/urdf.py
genesis/vis/viewer.py
tests/conftest.py
tests/test_rigid_physics.py
tests/utils.py

This PR unifies parsing of MJCF and URDF files to rely systematically on Mujoco internal parser if possible. This may fail because some mesh format for visual geometries are not supported my Mujoco, notably Collada `.dae`. In this case, falling back to the now legacy custom URDF parser. Besides, links and joints ordering should now better align with Mujoco, notably world would be in front of the kinematic string if any.
* Improve 'libigl' API workaround.
* Add utils to properly redirect libc stderr.
* Unify MJCF and URDF loading to avoid discrepancies if possible.
* Fix grapsing bottle example.
Related to Genesis-Embodied-AI/Genesis/issues/1135
Many fields are missing in URDF files to uniquely initialise the physics. Currently, Genesis is relying on default values that are different from …

[BUG FIX] Unified scene loading for MJCF and URDF files.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_link.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/ext/urdfpy/urdf.py
genesis/options/morphs.py
genesis/utils/mjcf.py
genesis/utils/urdf.py
tests/test_rigid_physics.py
tests/utils.py

* Remove fragile and convoluted URDF/MJCF kinematic chain post-processing introduced by https://github.com/Genesis-Embodied-AI/Genesis/pull/1159. 
* Parse root index in URDF/MJCF files.
* Unify fixed link merging pre-processing for URDF and Drone morphs.
* Making the unit tests more robust to make sure mujoco consistent unit tests are still passing despite these changes.
Handling special cases increases maintenance burden. This should be avoid if possible.
Running the unit tests successfully.

[BUG FIX] Simplify URDF/MJCF parser post-processing.

---

.github/workflows/linux-gpu.yml

Adding a timeout mechanism to make sure ressource always gets released at some point no matter what. Adding a Github step killing the Slurm job systematically, even if the Github Job is aborted.
Currently, Slurm containers may not be properly terminated, mainly if the job is aborted. This is an issue as it will hold ressources that may never be released automatically.

[MISC] More robust CI slurm container lifetime management.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_joint.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/engine/solvers/tool_solver.py
tests/test_rigid_physics.py

* Only apply collision pairs filtering based on 'contype', 'conaffinity' bitmasks to geometries associated with the same entity (eventually having different roots)
* Fix constraint solver not cleared if collisions and joint limits are disabled whereas there are some equality constraints
* Fix 'invweight' not being updated (equals to zero) for the root joint of URDF morph when 'fixed=False'
Resolves Genesis-Embodied-AI/Genesis/issues/1135

[BUG FIX] Fix 'fixed=False' support for URDF and Drone morph.

---

.github/workflows/linux-gpu.yml
README_CN.md
README_FR.md
README_JA.md
README_KR.md
genesis/engine/entities/fem_entity.py
genesis/engine/entities/rigid_entity/rigid_joint.py
genesis/options/morphs.py
genesis/utils/geom.py
genesis/utils/mesh.py
genesis/vis/rasterizer_context.py
pyproject.toml
tests/conftest.py
tests/run_benchmarks.py
tests/test_rigid_benchmarks.py
tests/test_rigid_physics.py
tests/utils.py

* Improve the reliability / compliance of benchmark infra to make sure it runs fine on all commits from latest official release on PyPI (`v0.2.1`) to current main branch.
* Best effort to make metrics comparable between commits by enforcing equivalent options over the whole history whenever possible
* Add monitoring of compilation time
* Push data on WanDB server (will be released publicly soon) for performance monitoring
* Fix FEM support on Apple Metal.
Related to Genesis-Embodied-AI/Genesis/issues/1155
Related to Genesis-Embodied-AI/Genesis/issues/412
Continuous monitoring of the performance enables to detect regressions as soon as possible, which makes it dramatically easier to diagnose the root, and in turns, come up with effective mitigations. Beyond that, having quantitative …

[MISC] Add compile- and run-time performance monitoring.

---

genesis/_main.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/ext/pyrender/shader_program.py
genesis/options/textures.py

* Clearer exception traceback in case of invalid mask for nested data accessor.
* Fix support of numpy scalar types for pyrender shader.
* Fix weird bug caused by passing int color dtype.
* Fix 'gs view' utility.
* Fix URDF parsing legacy fallback
Supersedes https://github.com/Genesis-Embodied-AI/Genesis/pull/1255
Resolves Genesis-Embodied-AI/Genesis/issues/1236
Related to Genesis-Embodied-AI/Genesis/discussions/1250

[BUG FIX] Various minor bug fixes.

---

pyproject.toml
tests/test_rigid_physics.py
tests/utils.py

* Remove dedicated worker group for unit tests requiring hugging face assets. 
* Switch from loadgroup to worksteal pytest xdist distributed job scheduler.
Historically, one single worker was executing all unit tests relying on Hugging Face dataset to avoid hitting API limit rate issues. This is significantly slowing down the whole pipeline on machines having more than 16 threads as this worker would have to execute multiple times more unit tests than all the other workers, so all the others will be waiting for it to complete. This guard is now longer necessary now that a more robust download mechanism has been implemented. This also allows for switching to a more efficient job scheduler, namely `worksteal` that can reassign unit tests to workers that are already done with their own …

[MISC] More efficient unit test distribution across workers.

---

genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/ext/pyrender/jit_render.py
genesis/ext/pyrender/numba_gl_wrapper.py
genesis/ext/pyrender/offscreen.py
genesis/ext/pyrender/platforms/egl.py
genesis/ext/pyrender/primitive.py
genesis/ext/pyrender/renderer.py
genesis/ext/pyrender/scene.py
genesis/ext/pyrender/viewer.py
genesis/vis/rasterizer.py
genesis/vis/rasterizer_context.py
genesis/vis/viewer.py
genesis/vis/visualizer.py

* Pass `shadow` and `plane_reflection` optional argument to low-level Pyrender offscreen rasterizer.
* Dynamically update scene bounds to fix shadow clipping issues 
Resolves Genesis-Embodied-AI/Genesis/issues/1264
Resolves Genesis-Embodied-AI/Genesis/issues/1279
Shadows and plane reflections were forcibly disabled by mistake in a previous PR of myself intended to make rendering fully deterministic. Besides, shadow clipping area is currently only computed once at init of the simulation, this leads to shadow clipping issues, especially when rendering floating base entities that are spanning a small area (e.g. a single ball).

[BUG FIX] Fix shadows and plane reflection for offscreen rendering.

---

genesis/utils/tools.py

Timers did not call ti.sync on create/reset when created with ti_sync=True parameter.
This caused invalid timings on the first call to timer.stamp().
Added ti.sync() call to Timer.reset()
Detailed profiling of sim on GPU

[BUG FIX] Timers did not call ti.sync on create/reset

---

genesis/options/morphs.py
genesis/utils/terrain.py

Added feature that allows user to upload a scalable texture "uv_scale" to the terrain instead of always being the default white one. 
Resolves #1252 
Without pattern:
With pattern:
Code to reproduce: 
```
from genesis import gs
gs.init(backend=gs.cpu)
scene = gs.Scene(show_viewer=True)
scene.add_entity(
surfaces.Rough(
roughness=0.3,
diffuse_texture=gs.textures.ImageTexture(image_path="genesis/assets/textures/checker.png"),
),
morph=gs.morphs.Terrain(
n_subterrains=(3, 3),
horizontal_scale=0.25
subterrain_types="wave_terrain",
uv_scale=9.0,
subterrain_parameters={"wave_terrain": {"amplitude": 0.2}},
),
)
scene.build()
for _ in range(500):
scene.step()
```

[Feature] Terrain texture user option

---

tests/test_rigid_benchmarks.py

Flush benchmarking results after each test
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/1332
Having to wait until all benchmarking tests have run in order to see the results
Running the benchmark script
```
pytest -svx tests/test_rigid_benchmarks.py -m benchmarks -sv
```

[FEATURE] Flush benchmarking results after each test

---

.github/CONTRIBUTING.md
genesis/engine/materials/FEM/elastic.py
genesis/engine/simulator.py
genesis/engine/solvers/fem_solver.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp.py
genesis/engine/solvers/rigid/mpr_decomp.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/utils/bvh.py
genesis/utils/tools.py
tests/test_rigid_benchmarks.py
tests/test_rigid_physics.py

* Disable timers by default.
* Fix compiler warnings for excessive inlining.
* Fix running benchmarks sequentially.
* Fix benchmark master worker id shadowing.
* Fix contribution guidelines.
* Re-enable warning for exceeding max collision pairs.
* Offset geometry centers for MPR only if necessary.
* Fix MPR warm-start infinite loop edge case.
Note that no unit test has been added for this MPR edge-case because it is too extremely difficult to trigger reliably. That would be too much work for not enough value.
Resolves Genesis-Embodied-AI/Genesis/issues/1123

[BUG FIX] Fix MPR warm-start infinite loop edge case.

---

genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/mpr_decomp.py
tests/test_rigid_physics.py

* Exposing low-level MPR interface allowing to explicitly passing the desired geometries' center as input argument of MPR
The collision detection algorithm from ANY vs TERRAIN is based on MPR under the hood. This involves dynamically computing the "center" of terrain by is modifying `geoms_info[i_gb].center` on-the-fly. This should be avoided because it creates collisions when dealing with batched environments.
This bug was uncovered by passing `cfg_optimization=False` to `taichi.init` method. Taichi's optimisations are apparently hiding the bug, possibly because of some temporary variable elision of something. But it should have failed from the start.
Related to https://github.com/Genesis-Embodied-AI/Genesis/issues/1329

[BUG FIX] Fix terrain collision detection.

---

examples/drone/hover_env.py

Currently, `HoverEnv.reward_scales` is a shadow reference of `reward_cfg["reward_scales"]`, so later modification on `self.reward_scales` will affect `reward_cfg["reward_scales"]`, leading to wrong reward_cfg in `cfgs.pkl`.

[BUG FIX] Fix pickling of 'reward_cfg["reward_scales"]' in hover example

---

genesis/vis/camera.py
tests/test_rigid_physics.py

When running in parallel environments, while attaching the camera to the link, you need to specify the environment index (`env_idx`) for each camera. This offsets the local Transform (T) to the corresponding environment offset
```py
n_envs = 4
cams = [scene.add_camera(GUI=True, fov=70) for _ in range(n_envs)]
for nenv, cam in enumerate(cams):
cam.attach(franka.get_link("hand"), np.eye(4), env_idx=nenv)
```
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/1016
[Previous PR](https://github.com/Genesis-Embodied-AI/Genesis/pull/618) introduced mounting cameras to the rigid body links (example: robot end-effector). However it [did not support](https://github.com/Genesis-Embodied-AI/Genesis/pull/618#issuecomment-2999769709) running such mounted cameras in parallel environments.
To …

[FEATURE] Allow mounted cameras to be run in parallel simulations

---

genesis/options/textures.py
tests/test_mesh.py

Auto-converts all float / bool / ≥9-bit integer images to uint8.
Expands grayscale (H,W) / (H,W,1) → RGB and L+A (H,W,2) → RGBA
Addresses: #1322

[FEATURE] URDF-GLB import: support non-uint8 + 1/2-channel textures

---

genesis/engine/coupler.py
genesis/engine/simulator.py
genesis/engine/solvers/base_solver.py
genesis/engine/solvers/fem_solver.py
genesis/engine/solvers/mpm_solver.py
genesis/engine/solvers/pbd_solver.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/engine/solvers/sf_solver.py
genesis/engine/solvers/sph_solver.py
genesis/engine/solvers/tool_solver.py
tests/test_rigid_physics.py

This PR introduces support for environment-specific gravity settings. Different environments in the simulation can now have distinct gravity configurations, enabling more flexible and realistic physics behavior tailored to each context.
Example use case with two spheres: 
```
import torch
gs.init(backend=gs.cpu)
sim_options=gs.options.SimOptions(
dt=0.01,
substeps=1,
),
)
sphere = scene.add_entity(gs.morphs.Sphere())
scene.build(n_envs=2)
scene.sim.set_gravity(torch.tensor([0.0, 0.0, -9.8]), envs_idx=0)
scene.sim.set_gravity(torch.tensor([0.0, 0.0, 9.8]), envs_idx=1)
for _ in range(200):
scene.step()
```
Addresses: #1113 
Below is a video demonstrating two parallel environments one with more negative gravity making the drone fall …

[FEATURE] Environment-wise gravity

---

genesis/engine/entities/rigid_entity/rigid_link.py
genesis/ext/pyrender/interaction/aabb.py
genesis/ext/pyrender/interaction/vec3.py
genesis/ext/pyrender/interaction/viewer_interaction.py
genesis/ext/pyrender/interaction/viewer_interaction_base.py
genesis/ext/pyrender/viewer.py

Objects can be held with LMB. 
When objects are held, camera rotation (via mouse-drag) is suspended.
Temporary implementation of object movement is added, where only position is updated, not velocities, so that causes interpenetrations of objects.
* Add simple box-moving interaction.
* Lazy load tensor in vec3.py, add Vec3/Quat.from_tensor/from_array.
* Rename oobb to obb.
* Vec3/Quat.as_tensor() is now a method.
Allow moving of objects and kinematic chains by using external user force.
Manual testing only

[MISC] Add viewer code to handle moving objects

---

genesis/__init__.py
genesis/engine/bvh.py
genesis/engine/coupler.py
genesis/engine/entities/pbd_entity.py
genesis/engine/force_fields.py
genesis/engine/solvers/fem_solver.py
genesis/engine/solvers/mpm_solver.py
genesis/engine/solvers/pbd_solver.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/engine/solvers/sph_solver.py
genesis/utils/geom.py
tests/test_bvh.py
tests/test_fem.py

* Fix support of boolean taichi field on Apple Metal by using 'ti.i32' instead of 'ti.u1'.
* Fix support of Apple Metal for LBVH by emulating 'ti.u64' with 'ti.types.vector(2, ti.u32)'.
* Fix 'axis_angle_to_R' float32 suport.
* Fix 'inv_T' geom utils.
* Fix 'test_linear_corotated_sphere_fall_implicit_fem_sap_coupler' not passing on GPU.
The ambition of Genesis is to be fully cross-platform (Windows OS, Linux OS and Mac OS) for both CPU and GPU computations. Apple Metal comes with several limitations, notably lack of support for 64bits precision algebra. Because of this, some unit tests are currently not passing when running on GPU backend (`pytest -v --backend gpu "./tests"`).

[BUG FIX] Fix support of Apple Metal.

---

genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_joint.py
genesis/engine/solvers/rigid/constraint_solver_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp_island.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/options/morphs.py

* Add drone morph option to add tiny angular damping on floating base by default.
* Remove redundant 'root_COM' link state.
Resolves Genesis-Embodied-AI/Genesis/issues/909
Supersedes Genesis-Embodied-AI/Genesis/pull/1348
```python
import torch
from hover_env import HoverEnv
gs.init(backend=gs.cpu, precision="32", logging_level="error", seed=0)
env = HoverEnv(
env_cfg={
"num_actions": 4,
"termination_if_roll_greater_than": 180,  # degree
"termination_if_pitch_greater_than": 180,
"termination_if_close_to_ground": 0.1,
"termination_if_x_greater_than": 3.0,
"termination_if_y_greater_than": 3.0,
"termination_if_z_greater_than": 2.0,
"base_init_pos": [0.0, 0.0, 1.0],
"base_init_quat": [1.0, 0.0, 0.0, 0.0],
"episode_length_s": 15.0,
"at_target_threshold": 0.1, …
```

[BUG FIX] Prevent unrealistic angular velocity of Drone entities causing numerical instability.

---

genesis/engine/entities/rigid_entity/rigid_entity.py

The joint `dofs_invweight` size is inconsistent with `n_dofs`. Therefore, it occasionally threw an `out_of_bound` error on Windows platform when `debug=False` in Taichi initialization. When `debug=True`, it always throws an error on every platform for `test_convexify` test.
```
E           taichi.lang.exception.TaichiAssertionError: 
E           [kernel=_kernel_init_dof_fields_c294_0] Out of bound access to ndarray at arg 3 with indices [8]
E           File "/home/sanghyun/Documents/Genesis/genesis/engine/solvers/rigid/rigid_solver_decomp.py", line 645, in _kernel_init_dof_fields:
E                       dofs_info[I].invweight = dofs_invweight[i]
E                                                ^^^^^^^^^^^^^^^^^
```

[BUGFIX] Fix the size of joint dofs_invweight

---

genesis/ext/pyrender/jit_render.py
genesis/ext/pyrender/viewer.py
genesis/vis/rasterizer.py
genesis/vis/rasterizer_context.py
genesis/vis/viewer.py
genesis/vis/visualizer.py

* Fix segmentation node removal.
* Cleanup rendering context state update.
Having all rendering backend managing their own context update state induces additional boilerplate without any advantage. It should be centralised in the context itself. Moreover, the viewer initialisation logic is overly complicated and should be simplified. 
`python examples/rigid/single_franka.py --vis`

[BUG FIX] Fix broken interactive viewer.

---

genesis/engine/solvers/rigid/array_class.py
genesis/engine/solvers/rigid/collider_decomp.py

This PR contains the following:
1. Made `max_collision_pairs_broad`, and set the value of it as 20x of `max_collision_pairs`. This is because we usually get much larger number of collision pairs during the broad phase than the narrow phase.
2. Removed duplicate `ConstraintState`.
3. Removed unnecessary fields in `ColliderState`.
As shown in the video below, if we do not allow large `max_collisions_pair` for the broad phase, some of the collision pairs are ignored and are not detected, even when the number of final collision pairs after the narrow phase is small. In the video below, it ends up in falling objects error. 
[Screencast from 2025-07-14 17-09-04.webm](https://github.com/user-attachments/assets/cca85ab4-8673-478f-bda8-7d76ae …

[BUGFIX] Made max_collision_pairs for broad phase larger

---

examples/rigid/accelerometer_franka.py
examples/rigid/closed_loop.py
examples/rigid/control_mesh.py
examples/rigid/diffik_controller.py
examples/rigid/domain_randomization.py
examples/rigid/franka_cube.py
examples/rigid/ik_custom_chain.py
examples/rigid/ik_duck.py
examples/rigid/ik_franka.py
examples/rigid/ik_franka_batched.py
examples/rigid/ik_shadow_hand.py
examples/rigid/merge_entities.py
examples/rigid/set_phys_attr.py
examples/rigid/single_franka.py
examples/rigid/single_franka_envs.py
examples/rigid/terrain_height_field.py
examples/rigid/terrain_subterrain.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_link.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/ext/pyrender/mesh.py
tests/test_rigid_physics.py

When calling `entity.get_AABB()` for a rigid entity, following error occured:
```
AttributeError: 'RigidSolver' object has no attribute '_func_update_verts_for_geom'
```
To reproduce the code, run:
```
gs.init(backend=gs.gpu, logging_level='debug')
options_mapping = {
'sim_options': gs.options.SimOptions,
'vis_options': gs.options.VisOptions,
'coupler_options': gs.options.BaseCouplerOptions,
'rigid_options': gs.options.RigidOptions,
'mpm_options': gs.options.MPMOptions,
'profiling_options': gs.options.ProfilingOptions,
'viewer_options': gs.options.ViewerOptions,
}
scene_args = {'show_viewer': False, 'vis_options': {'shadow': True, 'background_color': [0.04, 0.08, 0.12]}, 'profiling_options': {'show_FPS': True}, 'sim_options': {'dt': 0.01, 'substeps': 5, 'gravity': [0, …
```

[BUG FIX] Fix errors in APIs that are used by rigid examples

---

examples/rigid/single_franka_envs.py
genesis/ext/pyrender/interaction/viewer_interaction_base.py
genesis/ext/pyrender/jit_render.py
genesis/ext/pyrender/mesh.py
genesis/ext/pyrender/renderer.py
genesis/ext/pyrender/scene.py
genesis/ext/pyrender/viewer.py
genesis/vis/rasterizer_context.py
genesis/vis/visualizer.py
tests/test_render.py

Markers added via `draw_debug_*` API are not "invisible markers" instead of physical objects. In that sense, they are only rendered on the onscreen graphical windows, and do not cast shadow and reflection on the floor. They are not rendered on any of the camera ouputs, i.e. RGB, depth map and segmentation map.
Resolves Genesis-Embodied-AI/Genesis/issues/942
Running the example script 'single_franka_envs.py'.

Do not consider markers as physical objects for rendering.

---

genesis/engine/simulator.py
genesis/engine/solvers/base_solver.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
tests/test_rigid_physics.py

Allow for `set_gravity` per env
`set_gravity` was first introduced in https://github.com/Genesis-Embodied-AI/Genesis/pull/1324
Previous implementation did not properly set gravity per environment; taichi field should be set using kernel (no slicing)
Updated `test_rigid_physics.py`

[BUG FIX] Fix gravity setters.

---

genesis/engine/entities/rigid_entity/rigid_entity.py

Parse geometry-specific friction coefficient if and only if material friction coefficient is undefined.
Global material friction coefficient should have higher priority than pre-defined URDF / MJCF geometry-specific friction coefficient. This would better aligns with what is done for primitive geometries and meshes, and probably less confusing / error prone for the end-user.

[BUG FIX] Fix material friction being ignore when parsing URDF/MJCF files.

---

.github/workflows/generic.yml
pyproject.toml

Automatically deploy wheels on PyPI.

---

genesis/engine/entities/particle_entity.py
genesis/engine/materials/MPM/elasto_plastic.py
genesis/options/surfaces.py
genesis/utils/particle.py
genesis/utils/path_planing.py
genesis/vis/rasterizer_context.py
pyproject.toml
tests/test_deformable_physics.py
tests/test_render.py

Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/1523
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/1524

[MISC] Migrate to native Python API for 'splashsurf'.

---

genesis/engine/scene.py
genesis/ext/pyrender/offscreen.py
genesis/ext/pyrender/viewer.py
genesis/vis/camera.py
genesis/vis/rasterizer.py
genesis/vis/raytracer.py
tests/test_render.py

* Fix Rasterizer video recording.
* Fix RayTracer camera initialization.
* Fix support of RayTracer on MacOS.
* Fix support of OSMesa backend for Rasterizer.
* Improve exception handling for 'Rasterizer.render_camera'.
* Enable antialiasing by default for BatchRender.
Resolves Genesis-Embodied-AI/Genesis/issues/1535

[BUG FIX] Fix various rendering bugs.

---

examples/rigid/single_franka_batch_render.py
genesis/engine/scene.py
genesis/vis/batch_renderer.py
genesis/vis/camera.py
genesis/vis/visualizer.py

* Enable to use PyRenderer camera to render along with Madrona Batched renderer
* Only add rasterizer camera if needed instead of systematically as before
This will be useful for monitoring the training (logging eval video) in different resolution from what policy sees (e.g., HD camera for human monitoring and 64x64 for policy input) in a headless environment (like a server) where viewer is not available or when you don't want to use viewer to prevent slow down for the entire training.
```bash
python examples/rigid/single_franka_batch_render.py -r # batch_renderer only
python examples/rigid/single_franka_batch_render.py -r -d # batch_renderer + rasterizer for debug
```

[FEATURE] Add debug camera for monitoring.

---

genesis/engine/scene.py
genesis/engine/simulator.py
genesis/options/__init__.py
genesis/options/sensors.py
genesis/sensors/base_sensor.py
genesis/sensors/sensor_manager.py
genesis/utils/ring_buffer.py
genesis/vis/camera.py

Add SensorManager to Simulator. Sensor classes can now have per-scene multi-sensor caching.
Rigid Tactile Sensors https://github.com/Genesis-Embodied-AI/Genesis/pull/1451 will be rebased on this PR.
IMU Sensor https://github.com/Milotrince/Genesis/pull/1 is also based on this PR. (I can't do a "stacked PR" directly in Genesis repo since my branch doesn't live there, which is why the PR currently lives in my fork of Genesis)
The current sensor implementation does not allow for caching across multiple sensors, and usage is un-Genesis-like (unintuitive, e.g. does not align with `add_camera` pattern). See new [IMU](https://github.com/Milotrince/Genesis/pull/1) for an implementation/usage example.
Will add tests per sensor.

[FEATURE] Add dedicated sensor manager.

---

genesis/engine/mesh.py
genesis/ext/pyrender/renderer.py
genesis/ext/pyrender/viewer.py
genesis/utils/hybrid.py
genesis/utils/mesh.py

* Delay imports are very slow and not used in most common workflow
Importing Genesis can take up to 6 seconds on Mac OS. After this PR, it should take around 2 seconds.
Running `single_franka.py --vis` example on Mac OS and Linux (for `run_in_thread` set to False and True).

[MISC] Faster Genesis import.

---

genesis/engine/solvers/rigid/constraint_solver_decomp.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/utils/array_class.py
tests/test_render.py
tests/test_rigid_physics.py

* Properly reset the number of friction loss constraints
Resolves https://github.com/Genesis-Embodied-AI/Genesis/issues/1553
Resolves https://github.com/Genesis-Embodied-AI/Genesis/discussions/1544

[BUG FIX] Fix joint friction loss.

---

.github/workflows/generic.yml
.github/workflows/production.yml
genesis/__init__.py
genesis/engine/couplers/legacy_coupler.py
genesis/engine/entities/pbd_entity.py
genesis/engine/entities/tool_entity/mesh.py
genesis/engine/solvers/fem_solver.py
genesis/engine/solvers/mpm_solver.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/engine/solvers/sph_solver.py
pyproject.toml
tests/conftest.py
tests/test_render.py
tests/test_rigid_physics.py
tests/utils.py

* Enable taichi debug mode for taichi >= 1.7.3
This would make debugging of out-of-memory access much easier

[MISC] Enable taichi debug mode in tests if possible.

---

tests/conftest.py
tests/test_bvh.py
tests/test_deformable_physics.py
tests/test_fem.py
tests/test_hybrid.py
tests/test_mesh.py
tests/test_pbd.py
tests/test_sensors.py
tests/test_utils.py

* Mark all unit tests that take less than 6min to run as required
* Add new mechanism to overwrite the default precision and use it for FEM unit tests
Currently, the production CI is running all the unit tests systematically, but not our small GPU-poor cross-platform runners. The latter only run a minimal set of so-called "required" tests that are considered fast enough (i.e. less than about 360s). This is a good compromise between reliability and cost efficiency. However, many tests that were eligible to this "required" flag were not marked as such by mistake. This is an issue because we are not testing our codebase as extensively as we could.
Besides, FEM tests must run with 64bits precision enabled regardless the backend that is being used, because of numerical instability issues. This …

[MISC] Improve unit test infrastructure.

---

.github/pull_request_template.md
genesis/engine/couplers/sap_coupler.py
genesis/engine/entities/hybrid_entity.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/solvers/rigid/constraint_solver_decomp.py
genesis/engine/solvers/rigid/constraint_solver_decomp_island.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/utils/array_class.py
tests/test_rigid_physics.py
tests/utils.py

* Fix primitive and mesh's COM
* Change low-level COM's name from `COM` to `root_COM` for clarity
* Add 'ref' option for 'get_links_pos' matching 'get_links_vel' public API.
Here are the simulation videos before and after the change
https://github.com/user-attachments/assets/eb011e6c-beb9-485a-90f3-5e33fa49d281
https://github.com/user-attachments/assets/a30773f1-92cb-4fa6-98a3-025b9e9cca63
- The initial COM for primitive and meshs are (0,0,0). We should set them to None and compute the inertial_pos based on their geometry
- The COM variable is used to represent root_COM, which is confusing.

[BUG FIX, CHANGING] Fix primitive and mesh's COM. Add 'ref' optional argument to 'get_links_pos'.

---

genesis/ext/isaacgym/terrain_utils.py
tests/test_rigid_physics.py

Currently, the `random_uniform_terrain` subterrain only creates a random height field along one axis, and duplicates it for each row, leading to horizontal bumps, like speed bumps or a washboard.
As this seems to be modeled after the [isaac lab terrain of the same name](https://github.com/isaac-sim/IsaacLab/blob/931679641ee84e1b4175c15b48f9286d44ba9b04/source/isaaclab/isaaclab/terrains/height_field/hf_terrains.py#L21), I believe it's intended to create a random terrain in both axes.
Resolves Genesis-Embodied-AI/Genesis#1748
* Brings this terrain to parity with issac lab
* Provides an effective rugged terrain for locomotion training.
I ported the code change from Isaac Lab and visually confirmed the result.
Run this example to verify: `python ./examples/rigid/terrain_subterrain.py`
I'm …

[BUG FIX] Randomize uniform terrain along both axes.

---

genesis/sensors/contact_force.py
genesis/utils/ring_buffer.py
tests/test_sensors.py

Sensor data cache was not being set properly from the ring buffer because the index was pointing to next (not yet updated) location instead of currently updated position.
https://github.com/Genesis-Embodied-AI/Genesis/issues/1760
Ran the script from issue above and made sure it is reading properly.
```
[Genesis] [13:54:58] [INFO] Running at 14.62 FPS.
FR Foot Contact Force   : [7.827377796173096, -1.3204383850097656, 6.888644695281982]
FR Foot Contact Force GT: [7.827377796173096, -1.3204383850097656, 6.888644695281982]
FL Foot Contact Force   : [8.133493423461914, -0.7074760794639587, 6.780436992645264]
FL Foot Contact Force GT: [8.133493423461914, -0.7074760794639587, 6.780436992645264]
```
Also added test in `test_sensors.py` to check exact match for delay

[BUG FIX] Contact sensors always returning zeros.

---

genesis/engine/solvers/rigid/collider_decomp.py
tests/test_rigid_physics.py

Fix #1727
The center of the object was wrong when the offset of a terrain is not zero.

[BUG FIX] Fix terrain with non-zero offset

---

examples/coupling/cloth_on_rigid.py
genesis/engine/bvh.py
genesis/engine/couplers/sap_coupler.py
genesis/engine/entities/particle_entity.py
genesis/engine/entities/rigid_entity/rigid_entity.py
genesis/engine/entities/rigid_entity/rigid_geom.py
genesis/engine/entities/rigid_entity/rigid_link.py
genesis/engine/solvers/fem_solver.py
genesis/engine/solvers/rigid/collider_decomp.py
genesis/engine/solvers/rigid/gjk_decomp.py
genesis/engine/solvers/rigid/rigid_solver_decomp.py
genesis/engine/states/entities.py
genesis/ext/pyrender/viewer.py
genesis/options/morphs.py
genesis/repr_base.py
genesis/utils/array_class.py
genesis/utils/path_planning.py
tests/test_bvh.py
tests/test_deformable_physics.py
tests/test_examples.py
tests/test_gstaichi.py
tests/test_integration.py
tests/test_rigid_physics.py

* Minor cleanup.
* Cleanup gstaichi and examples unit tests.
* Fix interactive viewer deadlock when failing to initialize the viewer on background thread.
* Remove 'is_free' that was confusing and partially redundant with 'is_fixed'.
* Only update vertices if necessary.
Resolves Genesis-Embodied-AI/Genesis/issues/1794

[MISC] Remove 'is_free' that was confusing and partially redundant with 'is_fixed'.
